mod admin;
mod admin_community;
mod ai_jobs;
mod admin_dashboard;
mod admin_moderation;
mod auth;
mod bounties;
mod certifications;
mod email_prefs;
mod enterprise_credits;
mod enterprise_kyc;
mod enterprise_pipeline;
mod enterprise_subscriptions;
mod challenge_tags;
mod challenge_teams;
mod challenges;
mod community;
mod contact;
mod developer;
mod deliverables;
mod dm;
mod enterprise;
mod enterprise_sso;
mod feed;
mod scim;
mod forum;
mod github;
mod guild;
mod projects;
mod enterprise_dashboard;
mod gamification;
mod geo;
mod health;
mod i18n;
mod legal;
mod legal_well_known;
mod leaderboard;
mod magic_link;
mod mentorship;
mod metrics;
mod notifications;
mod oauth;
mod openapi;
mod profile;
mod profile_extras;
mod public_api;
mod push;
mod reports;
mod review_queue;
mod sandbox;
mod skills;
mod slices;
mod social;
mod sponsored_challenges;
mod talent_lists;
mod talent_search;
mod talent_search_v2;
mod tenants;
mod tournament;
mod tracks;
mod user_profile;
mod webauthn;

pub use admin::admin_routes;
pub use admin_community::admin_community_routes;
pub use ai_jobs::ai_job_routes;
pub use admin_dashboard::admin_dashboard_routes;
pub use admin_moderation::admin_moderation_routes;
pub use auth::auth_routes;
pub use bounties::bounty_routes;
pub use certifications::certification_routes;
pub use email_prefs::email_prefs_routes;
pub use enterprise_credits::enterprise_credits_routes;
pub use enterprise_kyc::enterprise_kyc_routes;
pub use enterprise_pipeline::enterprise_pipeline_routes;
pub use enterprise_subscriptions::enterprise_subscription_routes;
pub use challenge_tags::challenge_tag_routes;
pub use challenge_teams::challenge_team_routes;
pub use challenges::challenge_routes;
pub use community::community_routes;
pub use contact::contact_routes;
pub use deliverables::deliverable_routes;
pub use developer::developer_routes;
pub use dm::dm_routes;
pub use enterprise::enterprise_routes;
pub use enterprise_sso::enterprise_sso_routes;
pub use feed::feed_routes;
pub use scim::scim_routes;
pub use forum::forum_routes;
pub use github::github_routes;
pub use guild::guild_routes;
pub use projects::project_routes;
pub use enterprise_dashboard::enterprise_dashboard_routes;
pub use gamification::gamification_routes;
pub use geo::geo_routes;
pub use health::health_routes;
pub use i18n::{i18n_routes, resolve_from_accept_language};
pub use legal::{analytics_consent, legal_routes, marketing_consent};
pub use legal_well_known::well_known_routes;
pub use leaderboard::leaderboard_routes;
pub use magic_link::magic_link_routes;
pub use mentorship::mentorship_routes;
pub use metrics::{init_metrics, metrics_routes, start_business_gauges};
pub use notifications::notification_routes;
pub use oauth::oauth_routes;
pub use openapi::openapi_routes;
pub use profile::profile_routes;
pub use profile_extras::profile_extras_routes;
pub use public_api::public_api_routes;
pub use push::push_routes;
pub use reports::report_routes;
pub use review_queue::review_queue_routes;
pub use sandbox::sandbox_routes;
pub use skills::skill_routes;
pub use slices::slice_routes;
pub use social::social_routes;
pub use sponsored_challenges::sponsored_routes;
pub use talent_lists::talent_list_routes;
pub use talent_search::talent_search_routes;
pub use talent_search_v2::talent_search_v2_routes;
pub use tenants::{ROOT_TENANT_ID, is_root_tenant, resolve_tenant_from_headers, tenant_routes};
pub use tournament::tournament_routes;
pub use tracks::track_routes;
pub use user_profile::user_profile_routes;
pub use webauthn::webauthn_routes;
