pub mod additional_products;
pub mod ai_attestations;
pub mod ai_companion;
pub mod ai_log;
pub mod ai_profile;
pub mod ai_queue;
pub mod ambassadors;
pub mod analytics;
pub mod api_metering;
pub mod apprentice_verification;
pub mod artefact_attestations;
pub mod artifact_registry;
pub mod ats;
pub mod attestation_certificate;
pub mod attestations;
pub mod audio_attestations;
pub mod audio_files;
pub mod audio_profile;
pub mod audit;
mod auth;
pub mod awards;
pub mod backup;
pub mod badge_engine;
pub mod balance_check;
pub mod batch;
pub mod beta_programs;
pub mod cache;
pub mod capabilities_engine;
pub mod ci_sync;
pub mod code_attestations;
pub mod code_portfolio;
pub mod cohorts;
pub mod collect;
pub mod collect_adapters;
pub mod consultations;
pub mod contest;
pub mod contest_prizes;
pub mod contest_reminders;
pub mod contests;
pub mod continuous;
pub mod craft_score;
pub mod credentials;
pub mod credit_value;
pub mod credits;
pub mod data_consent;
pub mod data_export;
pub mod data_licensing;
pub mod deliverables;
pub mod design_attestations;
pub mod design_auto_checks;
pub mod design_briefs;
pub mod design_cloud;
pub mod design_craft_score;
pub mod design_mentorship;
pub mod design_reviews;
pub mod design_uploads;
pub mod digest;
pub mod discord_announce;
pub mod disputes;
pub mod dm;
pub mod drip;
pub mod ecosystem;
mod email;
pub mod email_template;
pub mod email_theme;
pub mod engagements;
pub mod enterprise_sso;
pub mod entitlements;
pub mod erasure;
pub mod external_refresh;
pub mod external_signals;
pub mod feature_flags;
pub mod featured;
pub mod fedapay;
pub mod finance_line;
pub mod fingerprint;
pub mod forum;
pub mod fulfilment;
pub mod fx;
pub mod geo;
pub mod github;
pub mod goals;
pub mod guild;
pub mod hello_wall_mirror;
pub mod i18n;
pub mod interviews;
pub mod invoices;
pub mod launch_campaigns;
pub mod leaderboard;
pub mod ledger;
pub mod linear_sync;
pub mod llm_verifier;
pub mod maintainer_digest;
pub mod mentions;
pub mod mentoring_products;
pub mod mentorship_matching;
pub mod mission_billing;
pub mod mission_delivery;
pub mod mission_milestones;
pub mod missions;
pub mod mobile_money;
pub mod mobile_push;
pub mod next_challenges;
pub mod notify;
pub mod oauth;
pub mod og_card;
pub mod onboarding_recommendation;
pub mod ops_mentorship;
pub mod ops_onboarding;
pub mod ops_practice;
pub mod ops_profile;
pub mod orientations_playlist;
pub mod outbox;
pub mod payment_poller;
pub mod payment_webhook_sources;
pub mod payment_webhooks;
pub mod payout;
pub mod payout_adapters;
pub mod peer_matching;
pub mod plagiarism;
pub mod plagiarism_cases;
pub mod portfolio;
pub mod profile_readme_sync;
pub mod projects;
pub mod promotion_notify;
pub mod proof_hooks;
pub mod public_feed;
pub mod public_status;
pub mod push_sender;
pub mod queue;
pub mod ranks;
pub mod readme_sanitize;
pub mod reconciliation;
pub mod recruitment;
pub mod release;
pub mod reverse_recruitment;
pub mod review_queue;
pub mod reviews;
pub mod rls;
pub mod sales_pipeline;
pub mod sandbox;
pub mod saved_items;
pub mod scim;
pub mod seasons;
pub mod series;
pub mod session;
pub mod skill_tree;
pub mod skills;
pub mod slice_enrichment;
pub mod slice_ingestion;
pub mod slice_validation;
pub mod slices;
pub mod social;
pub mod sponsorship;
pub mod stewards;
pub mod storage;
pub mod streak_reminder;
pub mod stripe;
pub mod subscriptions;
pub mod talent_offers;
pub mod talent_wallet;
pub mod team_roles;
pub mod timeline;
pub mod tournament;
pub mod tracks;
pub mod trials;
pub mod validator_applications;
pub mod vouchings;
pub mod webauthn;
pub mod webhook;

pub use analytics::AnalyticsService;
pub use attestations::{Attestation, AttestationsService, CompagnonnageParams};
pub use auth::AuthService;
pub use deliverables::{DeliverablesService, PrMergedOutcome, PrMergedParams, TeamContributor};
#[allow(unused_imports)]
pub use dm::DmConversation;
pub use email::EmailService;
pub use geo::GeoService;
pub use leaderboard::LeaderboardService;
pub use portfolio::{PortfolioService, PublicUserSnapshot};
pub use queue::QueueService;
pub use review_queue::{
    QueueFilter as ReviewQueueFilter, ReviewQueueService, ReviewTask, SeniorityLevel,
};
pub use reviews::{
    ReviewsService, SubmitOutcome as ReviewSubmitOutcome, SubmitParams as ReviewSubmitParams,
    Verdict,
};
pub use sandbox::SandboxService;
pub use seasons::{CreateSeasonParams, Season, SeasonsService};
pub use session::SessionService;
pub use skills::{
    RecommendationSkillMatch, SkillFragmentOrder, SkillTalent, SkillsService, SliceRecommendation,
    TalentSearchFilter, UserSkillEnriched,
};
pub use slice_ingestion::{
    FigmaIngestor, GitHubIngestor, IngestReport, SliceIngestor, dispatch_ingestors,
    poll_all_github_projects,
};
pub use slices::{ListFilter as SlicesListFilter, SlicesService};
pub use stewards::{ProjectSteward, StewardsService};
pub use storage::StorageService;
pub use team_roles::{CreateSlotParams, MarketplaceSlot, TeamRolesService};
pub use tracks::{EligibilityCheck, Track, TrackProgress, TracksService, UserTrack};
pub use webauthn::WebauthnService;
pub use webhook::WebhookService;
