-- Phase P0 — Fondations du modèle cible.
-- Migration 0057 : seed initial de la table `skill_nodes`.
--
-- Ce fichier est AUTO-GÉNÉRÉ depuis docs/skill-nodes-seed.yaml
-- Ne pas éditer à la main. Re-générer avec :
--     python scripts/seed_skills_from_yaml.py
--
-- Contient :
--     47 catégories (parent_id = NULL)
--     290 skills atomiques (parent_id = FK vers leur catégorie)
--
-- Total : 337 lignes insérées dans skill_nodes.
--
-- L'ordre d'insertion est important : catégories d'abord (elles servent de
-- parent aux skills), puis skills atomiques dont le parent_id est résolu
-- par sous-requête via `slug`.

-- ═══════════════════════════════════════════════════════════════════
-- Étape 1 : Insérer les catégories (parent_id = NULL)
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO skill_nodes (slug, display_name, domain, parent_id, is_skilluv_specific)
VALUES
    ('web-fundamentals', 'Web fundamentals', 'code', NULL, FALSE),
    ('javascript-core', 'JavaScript core language', 'code', NULL, FALSE),
    ('typescript', 'TypeScript', 'code', NULL, FALSE),
    ('frontend-frameworks', 'Frontend frameworks', 'code', NULL, FALSE),
    ('rust', 'Rust', 'code', NULL, TRUE),
    ('python', 'Python', 'code', NULL, FALSE),
    ('backend-fundamentals', 'Backend fundamentals', 'code', NULL, FALSE),
    ('databases', 'Databases', 'code', NULL, FALSE),
    ('testing', 'Testing', 'code', NULL, FALSE),
    ('performance', 'Performance', 'code', NULL, FALSE),
    ('skilluv-platform-integrations', 'Skilluv platform integrations', 'code', NULL, TRUE),
    ('design-foundations', 'Design foundations', 'design', NULL, FALSE),
    ('ui-systems', 'UI systems and tokens', 'design', NULL, FALSE),
    ('figma-craft', 'Figma craft', 'design', NULL, FALSE),
    ('penpot-craft', 'Penpot craft (OSS alternative)', 'design', NULL, FALSE),
    ('ux', 'UX', 'design', NULL, FALSE),
    ('motion-and-interaction', 'Motion and interaction', 'design', NULL, FALSE),
    ('accessibility-design', 'Accessibility (design side)', 'design', NULL, FALSE),
    ('brand-and-identity', 'Brand and visual identity', 'design', NULL, FALSE),
    ('web-app-security', 'Web application security', 'security', NULL, FALSE),
    ('auth-security', 'Authentication security', 'security', NULL, FALSE),
    ('infrastructure-security', 'Infrastructure security', 'security', NULL, FALSE),
    ('cryptography-basics', 'Cryptography basics', 'security', NULL, FALSE),
    ('offensive-basics', 'Offensive security basics', 'security', NULL, FALSE),
    ('reporting', 'Vulnerability reporting', 'security', NULL, FALSE),
    ('llm-security', 'LLM and AI security', 'security', NULL, FALSE),
    ('godot-fundamentals', 'Godot fundamentals', 'game', NULL, FALSE),
    ('gameplay-programming', 'Gameplay programming', 'game', NULL, FALSE),
    ('2d-craft', '2D game craft', 'game', NULL, FALSE),
    ('3d-craft', '3D game craft', 'game', NULL, FALSE),
    ('game-design', 'Game design', 'game', NULL, FALSE),
    ('game-audio', 'Game audio', 'game', NULL, FALSE),
    ('multiplayer', 'Multiplayer', 'game', NULL, FALSE),
    ('written-communication', 'Written communication', 'soft_skills', NULL, FALSE),
    ('code-review', 'Code review', 'soft_skills', NULL, FALSE),
    ('collaboration', 'Collaboration', 'soft_skills', NULL, FALSE),
    ('problem-solving', 'Problem-solving', 'soft_skills', NULL, FALSE),
    ('leadership-technical', 'Technical leadership', 'soft_skills', NULL, FALSE),
    ('prompt-engineering', 'Prompt engineering', 'ai', NULL, FALSE),
    ('ai-integration', 'AI integration in products', 'ai', NULL, FALSE),
    ('ai-collaboration', 'Working with AI as a colleague', 'ai', NULL, FALSE),
    ('git-workflow', 'Git workflow', 'ops', NULL, FALSE),
    ('ci-cd', 'CI/CD', 'ops', NULL, FALSE),
    ('containers', 'Containers and orchestration', 'ops', NULL, FALSE),
    ('observability', 'Observability', 'ops', NULL, FALSE),
    ('incident-response', 'Incident response', 'ops', NULL, FALSE),
    ('infrastructure-provisioning', 'Infrastructure provisioning', 'ops', NULL, FALSE)
ON CONFLICT (slug) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════
-- Étape 2 : Insérer les skills atomiques avec parent_id résolu par slug
-- ═══════════════════════════════════════════════════════════════════

WITH new_skills (slug, display_name, description, domain, parent_slug, is_skilluv_specific) AS (
    VALUES
    ('html-semantic', 'Semantic HTML structure', 'Use the right HTML element for the right purpose (header, nav, main, article, section, aside, footer) instead of div soup.', 'code', 'web-fundamentals', FALSE),
    ('css-layout-flexbox', 'CSS Flexbox layout', NULL, 'code', 'web-fundamentals', FALSE),
    ('css-layout-grid', 'CSS Grid layout', NULL, 'code', 'web-fundamentals', FALSE),
    ('css-responsive-design', 'Responsive design with media queries and container queries', NULL, 'code', 'web-fundamentals', FALSE),
    ('css-tokens', 'CSS custom properties (design tokens)', NULL, 'code', 'web-fundamentals', FALSE),
    ('dom-manipulation', 'DOM manipulation without a framework', NULL, 'code', 'web-fundamentals', FALSE),
    ('web-components-basics', 'Web Components (Custom Elements, Shadow DOM)', NULL, 'code', 'web-fundamentals', FALSE),
    ('browser-networking', 'Browser networking (fetch, streams, service workers)', NULL, 'code', 'web-fundamentals', FALSE),
    ('js-closures', 'JavaScript closures', NULL, 'code', 'javascript-core', FALSE),
    ('js-promises', 'Promises and async/await', NULL, 'code', 'javascript-core', FALSE),
    ('js-modules', 'ES modules (import/export, dynamic import)', NULL, 'code', 'javascript-core', FALSE),
    ('js-array-methods', 'Array higher-order methods (map, filter, reduce, find)', NULL, 'code', 'javascript-core', FALSE),
    ('js-event-loop', 'Event loop and microtasks', NULL, 'code', 'javascript-core', FALSE),
    ('js-iterators-generators', 'Iterators and generators', NULL, 'code', 'javascript-core', FALSE),
    ('js-error-handling', 'JavaScript error handling patterns', NULL, 'code', 'javascript-core', FALSE),
    ('ts-basics', 'TypeScript basics (types, interfaces)', NULL, 'code', 'typescript', FALSE),
    ('ts-generics', 'TypeScript generics', NULL, 'code', 'typescript', FALSE),
    ('ts-utility-types', 'TypeScript utility types (Partial, Pick, Omit, Record)', NULL, 'code', 'typescript', FALSE),
    ('ts-discriminated-unions', 'Discriminated unions', NULL, 'code', 'typescript', FALSE),
    ('ts-conditional-types', 'Conditional and mapped types', NULL, 'code', 'typescript', FALSE),
    ('ts-strict-mode-hardening', 'Hardening a codebase with strict mode', NULL, 'code', 'typescript', FALSE),
    ('react-hooks', 'React hooks (useState, useEffect, useMemo, useCallback)', NULL, 'code', 'frontend-frameworks', FALSE),
    ('react-context', 'React Context API and providers', NULL, 'code', 'frontend-frameworks', FALSE),
    ('react-suspense', 'React Suspense and streaming', NULL, 'code', 'frontend-frameworks', FALSE),
    ('react-server-components', 'React Server Components', NULL, 'code', 'frontend-frameworks', FALSE),
    ('svelte-5-runes', 'Svelte 5 runes ($state, $derived, $effect)', NULL, 'code', 'frontend-frameworks', TRUE),
    ('svelte-stores', 'Svelte stores', NULL, 'code', 'frontend-frameworks', FALSE),
    ('sveltekit-routing', 'SvelteKit file-based routing', NULL, 'code', 'frontend-frameworks', TRUE),
    ('sveltekit-load-fns', 'SvelteKit load functions (server vs universal)', NULL, 'code', 'frontend-frameworks', TRUE),
    ('sveltekit-form-actions', 'SvelteKit form actions (progressive enhancement)', NULL, 'code', 'frontend-frameworks', TRUE),
    ('sveltekit-hooks', 'SvelteKit hooks (handle, handleFetch)', NULL, 'code', 'frontend-frameworks', TRUE),
    ('state-management-patterns', 'State management patterns (lifting, context, external stores)', NULL, 'code', 'frontend-frameworks', FALSE),
    ('tailwind-arbitrary-values', 'Tailwind arbitrary values and configuration', NULL, 'code', 'frontend-frameworks', FALSE),
    ('tailwind-4-cascade-layers', 'Tailwind CSS 4 with cascade layers', NULL, 'code', 'frontend-frameworks', TRUE),
    ('rust-ownership', 'Rust ownership and borrowing', NULL, 'code', 'rust', TRUE),
    ('rust-lifetimes', 'Rust lifetimes', NULL, 'code', 'rust', TRUE),
    ('rust-traits', 'Rust traits and trait bounds', NULL, 'code', 'rust', TRUE),
    ('rust-async', 'Rust async (tokio, futures)', NULL, 'code', 'rust', TRUE),
    ('rust-error-handling', 'Rust error handling with Result and ?', NULL, 'code', 'rust', TRUE),
    ('rust-derive-macros', 'Rust derive macros (Serde, thiserror, custom)', NULL, 'code', 'rust', TRUE),
    ('rust-tokio-select', 'tokio::select! for concurrent tasks', NULL, 'code', 'rust', TRUE),
    ('axum-route-handlers', 'Axum route handlers and extractors', NULL, 'code', 'rust', TRUE),
    ('axum-middleware', 'Axum middleware (Tower layers)', NULL, 'code', 'rust', TRUE),
    ('axum-custom-extractors', 'Axum custom extractors (FromRequestParts)', NULL, 'code', 'rust', TRUE),
    ('sqlx-compile-checked', 'SQLx compile-time checked queries', NULL, 'code', 'rust', TRUE),
    ('sqlx-migrations', 'SQLx migrations (safe DDL patterns)', NULL, 'code', 'rust', TRUE),
    ('tower-service-layer', 'Tower Service/Layer abstractions', NULL, 'code', 'rust', TRUE),
    ('python-typing', 'Python type hints (typing module, PEP 604)', NULL, 'code', 'python', FALSE),
    ('python-async', 'Python async/await', NULL, 'code', 'python', FALSE),
    ('python-context-managers', 'Python context managers (with, __enter__/__exit__)', NULL, 'code', 'python', FALSE),
    ('python-pydantic', 'Pydantic models and validation', NULL, 'code', 'python', FALSE),
    ('python-fastapi', 'FastAPI route + dependency injection', NULL, 'code', 'python', FALSE),
    ('python-uv-workflow', 'Python packaging with uv', NULL, 'code', 'python', TRUE),
    ('python-pytest', 'pytest fixtures and parametrization', NULL, 'code', 'python', FALSE),
    ('python-grpc-server', 'Python gRPC server implementation', NULL, 'code', 'python', TRUE),
    ('rest-design', 'REST API design (verbs, status codes, resource modeling)', NULL, 'code', 'backend-fundamentals', FALSE),
    ('graphql-schema-design', 'GraphQL schema design', NULL, 'code', 'backend-fundamentals', FALSE),
    ('grpc-service-design', 'gRPC service design and .proto files', NULL, 'code', 'backend-fundamentals', TRUE),
    ('pagination-strategies', 'Pagination strategies (offset, cursor, keyset)', NULL, 'code', 'backend-fundamentals', FALSE),
    ('idempotency', 'Idempotency keys for safe retries', NULL, 'code', 'backend-fundamentals', FALSE),
    ('webhook-design', 'Webhook design (delivery, retries, signatures)', NULL, 'code', 'backend-fundamentals', TRUE),
    ('webhook-signature-verify', 'Webhook signature verification (HMAC-SHA256)', NULL, 'code', 'backend-fundamentals', TRUE),
    ('rate-limiting-backend', 'Rate limiting implementation (token bucket, sliding window)', NULL, 'code', 'backend-fundamentals', TRUE),
    ('multi-tenant-isolation', 'Multi-tenant data isolation patterns', NULL, 'code', 'backend-fundamentals', TRUE),
    ('sql-joins', 'SQL joins (inner, left, right, full, cross)', NULL, 'code', 'databases', FALSE),
    ('sql-window-functions', 'SQL window functions', NULL, 'code', 'databases', FALSE),
    ('sql-cte', 'SQL common table expressions (CTE)', NULL, 'code', 'databases', FALSE),
    ('postgres-indexing', 'PostgreSQL indexing strategies (B-tree, GIN, partial)', NULL, 'code', 'databases', FALSE),
    ('postgres-jsonb', 'PostgreSQL JSONB querying and indexing', NULL, 'code', 'databases', FALSE),
    ('postgres-full-text', 'PostgreSQL full-text search (tsvector, GIN)', NULL, 'code', 'databases', FALSE),
    ('db-migration-safety', 'Safe database migrations (non-blocking DDL, backfill patterns)', NULL, 'code', 'databases', FALSE),
    ('db-transaction-isolation', 'Transaction isolation levels', NULL, 'code', 'databases', FALSE),
    ('redis-data-structures', 'Redis data structures (sorted sets, streams, pub/sub)', NULL, 'code', 'databases', TRUE),
    ('redis-caching-patterns', 'Redis caching patterns (cache-aside, write-through)', NULL, 'code', 'databases', FALSE),
    ('unit-testing', 'Writing focused unit tests', NULL, 'code', 'testing', FALSE),
    ('integration-testing', 'Integration testing (real DB, real HTTP)', NULL, 'code', 'testing', FALSE),
    ('e2e-testing-playwright', 'End-to-end testing with Playwright', NULL, 'code', 'testing', TRUE),
    ('test-doubles', 'Test doubles (mocks, stubs, fakes, spies)', NULL, 'code', 'testing', FALSE),
    ('property-based-testing', 'Property-based testing (QuickCheck-style)', NULL, 'code', 'testing', FALSE),
    ('rust-integration-testing', 'Rust integration testing (tokio::test, testcontainers)', NULL, 'code', 'testing', TRUE),
    ('test-fixture-design', 'Test fixture and factory design', NULL, 'code', 'testing', FALSE),
    ('perf-profiling', 'Profiling (CPU, memory, allocations)', NULL, 'code', 'performance', FALSE),
    ('perf-caching', 'Caching strategies (in-process, distributed, HTTP)', NULL, 'code', 'performance', FALSE),
    ('perf-database-query', 'Query optimization (EXPLAIN ANALYZE, N+1 detection)', NULL, 'code', 'performance', FALSE),
    ('perf-frontend-bundle', 'Frontend bundle size optimization', NULL, 'code', 'performance', FALSE),
    ('perf-lazy-loading', 'Lazy loading (code splitting, image loading)', NULL, 'code', 'performance', FALSE),
    ('perf-core-web-vitals', 'Core Web Vitals optimization (LCP, INP, CLS)', NULL, 'code', 'performance', FALSE),
    ('judge0-sandbox-integration', 'Judge0 sandbox integration and language config', NULL, 'code', 'skilluv-platform-integrations', TRUE),
    ('minio-s3-object-storage', 'MinIO / S3-compatible object storage', NULL, 'code', 'skilluv-platform-integrations', TRUE),
    ('mobile-money-psp', 'Mobile money PSP integration (Orange Money, MTN, Wave)', NULL, 'code', 'skilluv-platform-integrations', TRUE),
    ('stripe-integration', 'Stripe integration (payment intents, webhooks, subscriptions)', NULL, 'code', 'skilluv-platform-integrations', TRUE),
    ('enterprise-oidc-sso', 'Enterprise OIDC SSO implementation', NULL, 'code', 'skilluv-platform-integrations', TRUE),
    ('scim-provisioning', 'SCIM 2.0 user provisioning', NULL, 'code', 'skilluv-platform-integrations', TRUE),
    ('vapid-web-push', 'Native VAPID web push (RFC 8291, no Firebase)', NULL, 'code', 'skilluv-platform-integrations', TRUE),
    ('typography-basics', 'Typography basics (hierarchy, tracking, leading, x-height)', NULL, 'design', 'design-foundations', FALSE),
    ('typography-pairing', 'Font pairing and typographic system', NULL, 'design', 'design-foundations', FALSE),
    ('color-theory', 'Color theory (contrast, harmony, accessibility)', NULL, 'design', 'design-foundations', FALSE),
    ('color-system-design', 'Building a color system (semantic tokens, dark mode)', NULL, 'design', 'design-foundations', FALSE),
    ('composition-grids', 'Composition and grid systems', NULL, 'design', 'design-foundations', FALSE),
    ('whitespace-usage', 'Purposeful use of whitespace', NULL, 'design', 'design-foundations', FALSE),
    ('visual-hierarchy', 'Visual hierarchy (size, weight, contrast)', NULL, 'design', 'design-foundations', FALSE),
    ('design-tokens', 'Design tokens (W3C Community Group format)', NULL, 'design', 'ui-systems', FALSE),
    ('design-tokens-multi-brand', 'Multi-brand design tokens', NULL, 'design', 'ui-systems', FALSE),
    ('component-variants', 'Component variants and states', NULL, 'design', 'ui-systems', FALSE),
    ('design-system-thinking', 'Design system thinking (atoms, molecules, organisms)', NULL, 'design', 'ui-systems', FALSE),
    ('dark-mode-design', 'Dark mode / theming design', NULL, 'design', 'ui-systems', FALSE),
    ('responsive-components', 'Responsive component design (mobile-first)', NULL, 'design', 'ui-systems', FALSE),
    ('component-composition', 'Component composition patterns', NULL, 'design', 'ui-systems', FALSE),
    ('design-system-governance', 'Design system governance (versioning, contribution model)', NULL, 'design', 'ui-systems', FALSE),
    ('figma-auto-layout', 'Figma auto-layout mastery', NULL, 'design', 'figma-craft', FALSE),
    ('figma-variants', 'Figma component variants', NULL, 'design', 'figma-craft', FALSE),
    ('figma-variables-tokens', 'Figma variables and token modes', NULL, 'design', 'figma-craft', FALSE),
    ('figma-prototyping', 'Figma prototyping (interactive flows)', NULL, 'design', 'figma-craft', FALSE),
    ('figma-dev-mode-handoff', 'Figma Dev Mode handoff for developers', NULL, 'design', 'figma-craft', FALSE),
    ('figma-libraries-publishing', 'Figma library publishing and versioning', NULL, 'design', 'figma-craft', FALSE),
    ('penpot-basics', 'Penpot basics (self-hostable OSS design tool)', NULL, 'design', 'penpot-craft', FALSE),
    ('penpot-tokens', 'Design tokens in Penpot', NULL, 'design', 'penpot-craft', FALSE),
    ('user-flow-mapping', 'User flow mapping', NULL, 'design', 'ux', FALSE),
    ('wireframing', 'Low-fidelity wireframing', NULL, 'design', 'ux', FALSE),
    ('information-architecture', 'Information architecture', NULL, 'design', 'ux', FALSE),
    ('usability-heuristics', 'Nielsen usability heuristics', NULL, 'design', 'ux', FALSE),
    ('user-research-basics', 'User research basics (interviews, surveys)', NULL, 'design', 'ux', FALSE),
    ('usability-testing', 'Usability testing (moderated and unmoderated)', NULL, 'design', 'ux', FALSE),
    ('persona-development', 'Persona development', NULL, 'design', 'ux', FALSE),
    ('journey-mapping', 'Customer journey mapping', NULL, 'design', 'ux', FALSE),
    ('micro-interactions', 'Micro-interactions design', NULL, 'design', 'motion-and-interaction', FALSE),
    ('motion-principles', 'Motion principles (easing, timing, choreography)', NULL, 'design', 'motion-and-interaction', FALSE),
    ('prototyping-motion', 'Motion prototyping (Figma smart animate, Rive)', NULL, 'design', 'motion-and-interaction', FALSE),
    ('interaction-affordance', 'Designing interaction affordance', NULL, 'design', 'motion-and-interaction', FALSE),
    ('a11y-color-contrast', 'WCAG color contrast compliance', NULL, 'design', 'accessibility-design', FALSE),
    ('a11y-focus-states', 'Accessible focus states', NULL, 'design', 'accessibility-design', FALSE),
    ('a11y-motion-reduce', 'Motion accessibility (prefers-reduced-motion)', NULL, 'design', 'accessibility-design', FALSE),
    ('a11y-screen-reader-design', 'Designing for screen readers (labels, structure)', NULL, 'design', 'accessibility-design', FALSE),
    ('brand-identity-basics', 'Brand identity fundamentals', NULL, 'design', 'brand-and-identity', FALSE),
    ('logo-design-basics', 'Logo design (marks, wordmarks, monograms)', NULL, 'design', 'brand-and-identity', FALSE),
    ('brand-tokens-application', 'Applying brand tokens across surfaces', NULL, 'design', 'brand-and-identity', FALSE),
    ('owasp-top10-2025', 'OWASP Top 10 (2025) recognition', NULL, 'security', 'web-app-security', FALSE),
    ('sql-injection-detection', 'SQL injection detection', NULL, 'security', 'web-app-security', FALSE),
    ('xss-stored-reflected-dom', 'XSS (stored, reflected, DOM-based)', NULL, 'security', 'web-app-security', FALSE),
    ('csrf-protection', 'CSRF attack and protection', NULL, 'security', 'web-app-security', FALSE),
    ('idor-detection', 'IDOR (Insecure Direct Object Reference) detection', NULL, 'security', 'web-app-security', FALSE),
    ('ssrf-detection', 'SSRF (Server-Side Request Forgery) detection', NULL, 'security', 'web-app-security', FALSE),
    ('authz-vs-authn', 'Authorization vs authentication (distinguishing bugs)', NULL, 'security', 'web-app-security', FALSE),
    ('security-headers', 'Security headers (CSP, HSTS, X-Frame-Options)', NULL, 'security', 'web-app-security', FALSE),
    ('file-upload-security', 'File upload security (path traversal, MIME, size limits)', NULL, 'security', 'web-app-security', FALSE),
    ('jwt-security-pitfalls', 'JWT security pitfalls (none algo, key confusion)', NULL, 'security', 'auth-security', FALSE),
    ('session-management', 'Session management best practices', NULL, 'security', 'auth-security', FALSE),
    ('password-storage', 'Password storage (Argon2, bcrypt, scrypt)', NULL, 'security', 'auth-security', FALSE),
    ('mfa-implementation', 'MFA implementation (TOTP, WebAuthn)', NULL, 'security', 'auth-security', FALSE),
    ('oauth-flows', 'OAuth 2.0 flows and their pitfalls', NULL, 'security', 'auth-security', FALSE),
    ('passkey-webauthn', 'Passkeys and WebAuthn security', NULL, 'security', 'auth-security', TRUE),
    ('session-hijacking-defense', 'Session hijacking defense (cookies, fingerprinting)', NULL, 'security', 'auth-security', FALSE),
    ('container-security-basics', 'Container security (Docker, k8s pod security)', NULL, 'security', 'infrastructure-security', FALSE),
    ('secrets-management', 'Secrets management (vault, KMS, no-in-code)', NULL, 'security', 'infrastructure-security', FALSE),
    ('tls-configuration', 'TLS configuration hardening', NULL, 'security', 'infrastructure-security', FALSE),
    ('dependency-scanning', 'Dependency scanning and SBOM', NULL, 'security', 'infrastructure-security', FALSE),
    ('secrets-encryption-at-rest', 'Secrets encryption at rest (AES-256-GCM)', NULL, 'security', 'infrastructure-security', TRUE),
    ('symmetric-crypto', 'Symmetric cryptography (AES-GCM, ChaCha20-Poly1305)', NULL, 'security', 'cryptography-basics', FALSE),
    ('asymmetric-crypto', 'Asymmetric cryptography (RSA, ECDSA, Ed25519)', NULL, 'security', 'cryptography-basics', FALSE),
    ('hash-functions', 'Cryptographic hash functions (SHA-2, SHA-3, BLAKE)', NULL, 'security', 'cryptography-basics', FALSE),
    ('hmac-verification', 'HMAC signature verification', NULL, 'security', 'cryptography-basics', TRUE),
    ('key-management-basics', 'Key management basics (rotation, derivation)', NULL, 'security', 'cryptography-basics', FALSE),
    ('recon-passive', 'Passive reconnaissance', NULL, 'security', 'offensive-basics', FALSE),
    ('recon-active', 'Active reconnaissance', NULL, 'security', 'offensive-basics', FALSE),
    ('exploit-crafting', 'Basic exploit crafting for known CVEs', NULL, 'security', 'offensive-basics', FALSE),
    ('sandboxed-lab-practice', 'Practicing in sandboxed labs (HTB, TryHackMe)', NULL, 'security', 'offensive-basics', FALSE),
    ('post-exploitation-basics', 'Post-exploitation fundamentals', NULL, 'security', 'offensive-basics', FALSE),
    ('cvss-scoring', 'CVSS v3.1/v4 scoring', NULL, 'security', 'reporting', FALSE),
    ('cve-process', 'CVE process (requesting, publishing via CNA)', NULL, 'security', 'reporting', FALSE),
    ('responsible-disclosure', 'Responsible disclosure workflow', NULL, 'security', 'reporting', FALSE),
    ('writeup-quality', 'Writing a vulnerability report (impact, PoC, remediation)', NULL, 'security', 'reporting', FALSE),
    ('coordinated-disclosure-comm', 'Coordinated disclosure communication', NULL, 'security', 'reporting', FALSE),
    ('prompt-injection-detection', 'Prompt injection detection', NULL, 'security', 'llm-security', FALSE),
    ('llm-data-exfiltration', 'LLM data exfiltration prevention', NULL, 'security', 'llm-security', FALSE),
    ('rag-security', 'RAG pipeline security (retrieval poisoning)', NULL, 'security', 'llm-security', FALSE),
    ('llm-jailbreak-defense', 'LLM jailbreak defense in production apps', NULL, 'security', 'llm-security', FALSE),
    ('godot-node-tree', 'Godot scene and node tree design', NULL, 'game', 'godot-fundamentals', FALSE),
    ('gdscript-basics', 'GDScript basics', NULL, 'game', 'godot-fundamentals', FALSE),
    ('godot-signals', 'Godot signals (event-driven design)', NULL, 'game', 'godot-fundamentals', FALSE),
    ('godot-input-handling', 'Godot input handling', NULL, 'game', 'godot-fundamentals', FALSE),
    ('godot-resource-system', 'Godot Resource system (custom .tres)', NULL, 'game', 'godot-fundamentals', FALSE),
    ('godot-scene-inheritance', 'Godot scene inheritance and composition', NULL, 'game', 'godot-fundamentals', FALSE),
    ('state-machines-game', 'Finite state machines for game entities', NULL, 'game', 'gameplay-programming', FALSE),
    ('pathfinding-astar', 'A* pathfinding', NULL, 'game', 'gameplay-programming', FALSE),
    ('physics-2d-game', '2D physics (rigid bodies, collision layers)', NULL, 'game', 'gameplay-programming', FALSE),
    ('physics-3d-game', '3D physics fundamentals', NULL, 'game', 'gameplay-programming', FALSE),
    ('camera-controllers', 'Camera controllers (2D and 3D)', NULL, 'game', 'gameplay-programming', FALSE),
    ('inventory-systems', 'Inventory / item systems design', NULL, 'game', 'gameplay-programming', FALSE),
    ('dialogue-systems', 'Dialogue and branching narrative systems', NULL, 'game', 'gameplay-programming', FALSE),
    ('save-load-systems', 'Save/load systems (serialization patterns)', NULL, 'game', 'gameplay-programming', FALSE),
    ('pixel-art-basics', 'Pixel art basics', NULL, 'game', '2d-craft', FALSE),
    ('sprite-animation', 'Sprite sheet animation', NULL, 'game', '2d-craft', FALSE),
    ('2d-level-design', '2D level design (metroidvania, platformer)', NULL, 'game', '2d-craft', FALSE),
    ('tilemap-workflow', 'Tilemap workflow', NULL, 'game', '2d-craft', FALSE),
    ('2d-lighting', '2D dynamic lighting', NULL, 'game', '2d-craft', FALSE),
    ('parallax-scrolling', 'Parallax scrolling and depth', NULL, 'game', '2d-craft', FALSE),
    ('blender-modeling-basics', 'Blender modeling basics', NULL, 'game', '3d-craft', FALSE),
    ('blender-uv-unwrapping', 'Blender UV unwrapping', NULL, 'game', '3d-craft', FALSE),
    ('texturing-basics', 'Texturing basics (albedo, roughness, normal)', NULL, 'game', '3d-craft', FALSE),
    ('shaders-godot', 'Godot shader language basics', NULL, 'game', '3d-craft', FALSE),
    ('character-rigging-basics', 'Character rigging basics', NULL, 'game', '3d-craft', FALSE),
    ('3d-animation-basics', '3D animation basics (keyframes, IK)', NULL, 'game', '3d-craft', FALSE),
    ('game-feel', 'Game feel (juice, feedback, screen shake)', NULL, 'game', 'game-design', FALSE),
    ('gameplay-loop-design', 'Gameplay loop design', NULL, 'game', 'game-design', FALSE),
    ('difficulty-curve', 'Difficulty curve design', NULL, 'game', 'game-design', FALSE),
    ('onboarding-tutorials', 'Onboarding and tutorial design in games', NULL, 'game', 'game-design', FALSE),
    ('playtesting-methodology', 'Playtesting methodology', NULL, 'game', 'game-design', FALSE),
    ('sfx-integration', 'SFX integration and audio buses', NULL, 'game', 'game-audio', FALSE),
    ('music-loop-composition', 'Music loop composition for games', NULL, 'game', 'game-audio', FALSE),
    ('adaptive-music', 'Adaptive / dynamic music implementation', NULL, 'game', 'game-audio', FALSE),
    ('netcode-basics', 'Netcode basics (authoritative server, client prediction)', NULL, 'game', 'multiplayer', FALSE),
    ('anti-cheat-basics', 'Anti-cheat basics', NULL, 'game', 'multiplayer', FALSE),
    ('lobby-matchmaking', 'Lobby and matchmaking systems', NULL, 'game', 'multiplayer', FALSE),
    ('pr-description-quality', 'Writing a clear PR description', NULL, 'soft_skills', 'written-communication', FALSE),
    ('commit-message-quality', 'Writing clear commit messages (Conventional Commits)', NULL, 'soft_skills', 'written-communication', FALSE),
    ('technical-writing', 'Technical writing (docs, tutorials, RFCs)', NULL, 'soft_skills', 'written-communication', FALSE),
    ('incident-postmortem', 'Writing an incident post-mortem', NULL, 'soft_skills', 'written-communication', FALSE),
    ('bug-report-quality', 'Writing a reproducible bug report', NULL, 'soft_skills', 'written-communication', FALSE),
    ('readme-authoring', 'Writing a public README (mission + quick start + community)', NULL, 'soft_skills', 'written-communication', FALSE),
    ('adr-writing', 'Writing Architecture Decision Records (ADR)', NULL, 'soft_skills', 'written-communication', FALSE),
    ('code-review-etiquette', 'Code review etiquette (kind, specific, actionable)', NULL, 'soft_skills', 'code-review', FALSE),
    ('code-review-catching-bugs', 'Code review — catching subtle bugs', NULL, 'soft_skills', 'code-review', FALSE),
    ('code-review-teaching', 'Code review as teaching (explaining the why)', NULL, 'soft_skills', 'code-review', FALSE),
    ('review-rejection-well', 'Rejecting a PR with clarity and respect', NULL, 'soft_skills', 'code-review', FALSE),
    ('review-of-ai-generated', 'Reviewing AI-generated code critically', NULL, 'soft_skills', 'code-review', FALSE),
    ('async-communication', 'Async communication (Slack/Discord/GitHub)', NULL, 'soft_skills', 'collaboration', FALSE),
    ('giving-feedback', 'Giving constructive feedback', NULL, 'soft_skills', 'collaboration', FALSE),
    ('receiving-feedback', 'Receiving feedback without defensiveness', NULL, 'soft_skills', 'collaboration', FALSE),
    ('mentoring-junior', 'Mentoring a junior contributor', NULL, 'soft_skills', 'collaboration', FALSE),
    ('pair-programming', 'Pair programming (driver/navigator)', NULL, 'soft_skills', 'collaboration', FALSE),
    ('technical-1on1', 'Facilitating technical 1-on-1 with a mentee', NULL, 'soft_skills', 'collaboration', FALSE),
    ('debugging-methodology', 'Systematic debugging methodology', NULL, 'soft_skills', 'problem-solving', FALSE),
    ('root-cause-analysis', 'Root cause analysis (5 whys, fishbone)', NULL, 'soft_skills', 'problem-solving', FALSE),
    ('scope-negotiation', 'Scope negotiation (saying no gracefully)', NULL, 'soft_skills', 'problem-solving', FALSE),
    ('stack-overflow-of-oneself', 'Structured self-unblocking (before asking for help)', NULL, 'soft_skills', 'problem-solving', FALSE),
    ('technical-decision-making', 'Making and defending technical decisions', NULL, 'soft_skills', 'leadership-technical', FALSE),
    ('project-scoping', 'Project scoping and slicing', NULL, 'soft_skills', 'leadership-technical', FALSE),
    ('stakeholder-communication', 'Stakeholder communication (non-technical)', NULL, 'soft_skills', 'leadership-technical', FALSE),
    ('roadmap-thinking', 'Roadmap thinking (near vs far horizon)', NULL, 'soft_skills', 'leadership-technical', FALSE),
    ('prompt-clarity', 'Prompt clarity and structure', NULL, 'ai', 'prompt-engineering', FALSE),
    ('few-shot-prompting', 'Few-shot prompting', NULL, 'ai', 'prompt-engineering', FALSE),
    ('chain-of-thought', 'Chain-of-thought prompting', NULL, 'ai', 'prompt-engineering', FALSE),
    ('prompt-robustness', 'Prompt robustness across models', NULL, 'ai', 'prompt-engineering', FALSE),
    ('system-prompt-design', 'System prompt design and role-setting', NULL, 'ai', 'prompt-engineering', FALSE),
    ('context-window-management', 'Context window management (chunking, priming)', NULL, 'ai', 'prompt-engineering', FALSE),
    ('llm-api-integration', 'LLM API integration (Anthropic, OpenAI, Mistral)', NULL, 'ai', 'ai-integration', FALSE),
    ('streaming-responses', 'Streaming LLM responses (SSE, chunked)', NULL, 'ai', 'ai-integration', FALSE),
    ('tool-use-orchestration', 'LLM tool use / function calling orchestration', NULL, 'ai', 'ai-integration', FALSE),
    ('rag-basics', 'RAG pipeline basics', NULL, 'ai', 'ai-integration', FALSE),
    ('llm-cost-optimization', 'LLM cost and latency optimization', NULL, 'ai', 'ai-integration', FALSE),
    ('llm-evals-design', 'LLM evals design (behavioral, safety, quality)', NULL, 'ai', 'ai-integration', FALSE),
    ('llm-guardrails', 'LLM guardrails (input filtering, output moderation)', NULL, 'ai', 'ai-integration', FALSE),
    ('ai-pair-programming', 'Effective AI pair programming', NULL, 'ai', 'ai-collaboration', FALSE),
    ('refactoring-ai-slop', 'Refactoring AI slop into maintainable code', NULL, 'ai', 'ai-collaboration', FALSE),
    ('ai-assisted-debugging', 'AI-assisted debugging effectively', NULL, 'ai', 'ai-collaboration', FALSE),
    ('ai-assisted-code-search', 'AI-assisted code search and exploration', NULL, 'ai', 'ai-collaboration', FALSE),
    ('ai-assisted-test-generation', 'AI-assisted test generation (with verification)', NULL, 'ai', 'ai-collaboration', FALSE),
    ('git-rebase-interactive', 'git rebase -i (squash, reword, edit)', NULL, 'ops', 'git-workflow', FALSE),
    ('git-bisect', 'git bisect for regression hunting', NULL, 'ops', 'git-workflow', FALSE),
    ('git-cherry-pick', 'git cherry-pick', NULL, 'ops', 'git-workflow', FALSE),
    ('git-conflict-resolution', 'Merge conflict resolution', NULL, 'ops', 'git-workflow', FALSE),
    ('git-reflog-recovery', 'git reflog for recovery', NULL, 'ops', 'git-workflow', FALSE),
    ('git-hooks', 'git hooks (pre-commit, commit-msg)', NULL, 'ops', 'git-workflow', FALSE),
    ('git-worktree', 'git worktree for parallel branches', NULL, 'ops', 'git-workflow', FALSE),
    ('git-signed-commits', 'Signed commits and verified identity', NULL, 'ops', 'git-workflow', FALSE),
    ('github-actions-basics', 'GitHub Actions workflows', NULL, 'ops', 'ci-cd', TRUE),
    ('github-actions-matrix', 'GitHub Actions matrix builds', NULL, 'ops', 'ci-cd', FALSE),
    ('ci-test-parallelization', 'CI test parallelization', NULL, 'ops', 'ci-cd', FALSE),
    ('ci-caching', 'CI dependency caching (npm, cargo, uv)', NULL, 'ops', 'ci-cd', FALSE),
    ('deploy-preview-environments', 'Preview environments for PRs', NULL, 'ops', 'ci-cd', FALSE),
    ('rollback-strategies', 'Deployment rollback strategies', NULL, 'ops', 'ci-cd', FALSE),
    ('canary-deploys', 'Canary and blue-green deploys', NULL, 'ops', 'ci-cd', FALSE),
    ('dockerfile-multi-stage', 'Multi-stage Dockerfile', NULL, 'ops', 'containers', FALSE),
    ('docker-compose-dev', 'docker-compose for local dev', NULL, 'ops', 'containers', TRUE),
    ('docker-image-hardening', 'Docker image hardening (distroless, non-root)', NULL, 'ops', 'containers', FALSE),
    ('k8s-basics', 'Kubernetes basics (pods, services, deployments)', NULL, 'ops', 'containers', FALSE),
    ('structured-logging', 'Structured logging (JSON, correlation IDs)', NULL, 'ops', 'observability', FALSE),
    ('prometheus-metrics', 'Prometheus metrics design', NULL, 'ops', 'observability', TRUE),
    ('distributed-tracing', 'Distributed tracing (OpenTelemetry)', NULL, 'ops', 'observability', FALSE),
    ('alerting-design', 'Alerting design (avoid alert fatigue)', NULL, 'ops', 'observability', FALSE),
    ('log-aggregation-loki', 'Log aggregation with Grafana Loki', NULL, 'ops', 'observability', FALSE),
    ('grafana-dashboards', 'Grafana dashboards (thoughtful, actionable)', NULL, 'ops', 'observability', FALSE),
    ('incident-triage', 'Incident triage (severity, priority)', NULL, 'ops', 'incident-response', FALSE),
    ('incident-communication', 'Incident communication (status pages, updates)', NULL, 'ops', 'incident-response', FALSE),
    ('runbook-writing', 'Runbook writing', NULL, 'ops', 'incident-response', FALSE),
    ('on-call-hygiene', 'On-call hygiene and handoff', NULL, 'ops', 'incident-response', FALSE),
    ('hetzner-vps-provisioning', 'Hetzner Cloud VPS provisioning', NULL, 'ops', 'infrastructure-provisioning', TRUE),
    ('reverse-proxy-nginx', 'Reverse proxy setup (Nginx / Caddy)', NULL, 'ops', 'infrastructure-provisioning', FALSE),
    ('tls-certbot', 'TLS certificates automation (Let''s Encrypt)', NULL, 'ops', 'infrastructure-provisioning', FALSE),
    ('backup-restore-postgres', 'PostgreSQL backup and restore', NULL, 'ops', 'infrastructure-provisioning', TRUE)
)
INSERT INTO skill_nodes (slug, display_name, description, domain, parent_id, is_skilluv_specific)
SELECT
    ns.slug,
    ns.display_name,
    ns.description,
    ns.domain,
    parent.id,
    ns.is_skilluv_specific
FROM new_skills ns
JOIN skill_nodes parent ON parent.slug = ns.parent_slug AND parent.parent_id IS NULL
ON CONFLICT (slug) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════
-- Vérification (commentaires — les COUNT ne s'exécutent pas dans une migration)
-- ═══════════════════════════════════════════════════════════════════
--
-- Après application, on doit avoir :
--     SELECT COUNT(*) FROM skill_nodes WHERE parent_id IS NULL;     -- 47 catégories
--     SELECT COUNT(*) FROM skill_nodes WHERE parent_id IS NOT NULL; -- 290 skills atomiques
--     SELECT COUNT(*) FROM skill_nodes;                             -- 337 total
