-- Each orientation's skills. `is_core` marks what a reviewer expects to see;
-- the rest are recommended. A slug that names nothing is silently dropped by
-- the JOIN, so the DO-block below asserts the exact edge count — a typo fails
-- the build, not a profile that quietly shows fewer skills than it should.

INSERT INTO orientation_skill_map (orientation_id, skill_id, is_core, is_recommended, weight)
SELECT o.id, s.id, v.is_core, NOT v.is_core, v.weight
  FROM (VALUES
    ('game-gameplay-programmer', 'game-gameplay-systems', TRUE, 1.0),
    ('game-gameplay-programmer', 'game-character-controller', TRUE, 1.0),
    ('game-gameplay-programmer', 'game-camera-systems', TRUE, 1.0),
    ('game-gameplay-programmer', 'game-save-load', TRUE, 1.0),
    ('game-gameplay-programmer', 'game-inventory-systems', TRUE, 1.0),
    ('game-gameplay-programmer', 'game-playtesting', TRUE, 1.0),
    ('game-gameplay-programmer', 'game-engine-godot', FALSE, 1.0),
    ('game-gameplay-programmer', 'game-engine-bevy', FALSE, 1.0),
    ('game-gameplay-programmer', 'game-web-builds', FALSE, 1.0),
    ('game-engine-programmer', 'game-engine-architecture', TRUE, 1.0),
    ('game-engine-programmer', 'game-ecs', TRUE, 1.0),
    ('game-engine-programmer', 'game-engine-extension', TRUE, 1.0),
    ('game-engine-programmer', 'game-frame-budget', TRUE, 1.0),
    ('game-engine-programmer', 'game-engine-bevy', FALSE, 1.0),
    ('game-engine-programmer', 'game-engine-godot', FALSE, 1.0),
    ('game-engine-programmer', 'game-tooling', FALSE, 1.0),
    ('game-graphics-programmer', 'game-rendering', TRUE, 1.0),
    ('game-graphics-programmer', 'game-shaders', TRUE, 1.0),
    ('game-graphics-programmer', 'game-gpu-particles', TRUE, 1.0),
    ('game-graphics-programmer', 'game-frame-budget', TRUE, 1.0),
    ('game-graphics-programmer', 'game-web-builds', FALSE, 1.0),
    ('game-graphics-programmer', 'game-engine-bevy', FALSE, 1.0),
    ('game-graphics-programmer', 'game-engine-godot', FALSE, 1.0),
    ('game-network-programmer', 'game-networking', TRUE, 1.0),
    ('game-network-programmer', 'game-authoritative-sync', TRUE, 1.0),
    ('game-network-programmer', 'game-rollback', TRUE, 1.0),
    ('game-network-programmer', 'game-matchmaking', TRUE, 1.0),
    ('game-network-programmer', 'game-live-services', FALSE, 1.0),
    ('game-network-programmer', 'game-playtesting', FALSE, 1.0),
    ('game-ai-programmer', 'game-ai-behaviour', TRUE, 1.0),
    ('game-ai-programmer', 'game-behaviour-trees', TRUE, 1.0),
    ('game-ai-programmer', 'game-pathfinding', TRUE, 1.0),
    ('game-ai-programmer', 'game-procgen', TRUE, 1.0),
    ('game-ai-programmer', 'game-gameplay-systems', FALSE, 1.0),
    ('game-ai-programmer', 'game-playtesting', FALSE, 1.0),
    ('game-tools-programmer', 'game-tooling', TRUE, 1.0),
    ('game-tools-programmer', 'game-editor-plugins', TRUE, 1.0),
    ('game-tools-programmer', 'game-asset-pipeline', TRUE, 1.0),
    ('game-tools-programmer', 'game-engine-godot', FALSE, 1.0),
    ('game-tools-programmer', 'game-engine-architecture', FALSE, 1.0),
    ('game-backend-programmer', 'game-live-services', TRUE, 1.0),
    ('game-backend-programmer', 'game-matchmaking', TRUE, 1.0),
    ('game-backend-programmer', 'game-save-load', TRUE, 1.0),
    ('game-backend-programmer', 'game-networking', FALSE, 1.0),
    ('game-systems-designer', 'game-systems-design', TRUE, 1.0),
    ('game-systems-designer', 'game-progression-design', TRUE, 1.0),
    ('game-systems-designer', 'game-balance', TRUE, 1.0),
    ('game-systems-designer', 'game-gdd', TRUE, 1.0),
    ('game-systems-designer', 'game-economy-design', FALSE, 1.0),
    ('game-systems-designer', 'game-playtesting', TRUE, 1.0),
    ('game-level-designer', 'game-level-design', TRUE, 1.0),
    ('game-level-designer', 'game-encounter-design', TRUE, 1.0),
    ('game-level-designer', 'game-open-world-design', TRUE, 1.0),
    ('game-level-designer', 'game-gdd', FALSE, 1.0),
    ('game-level-designer', 'game-playtesting', TRUE, 1.0),
    ('game-level-designer', 'game-engine-godot', FALSE, 1.0),
    ('game-narrative-designer', 'game-narrative-design', TRUE, 1.0),
    ('game-narrative-designer', 'game-branching', TRUE, 1.0),
    ('game-narrative-designer', 'game-worldbuilding', TRUE, 1.0),
    ('game-narrative-designer', 'game-environmental-story', TRUE, 1.0),
    ('game-narrative-designer', 'game-gdd', FALSE, 1.0),
    ('game-economy-designer', 'game-economy-design', TRUE, 1.0),
    ('game-economy-designer', 'game-monetisation-ethics', TRUE, 1.0),
    ('game-economy-designer', 'game-progression-design', TRUE, 1.0),
    ('game-economy-designer', 'game-balance', TRUE, 1.0),
    ('game-economy-designer', 'game-gdd', FALSE, 1.0),
    ('game-combat-designer', 'game-combat-design', TRUE, 1.0),
    ('game-combat-designer', 'game-combat-feel', TRUE, 1.0),
    ('game-combat-designer', 'game-balance', TRUE, 1.0),
    ('game-combat-designer', 'game-gdd', FALSE, 1.0),
    ('game-combat-designer', 'game-playtesting', TRUE, 1.0),
    ('game-3d-modeler-hardsurface', 'game-3d-hardsurface', TRUE, 1.0),
    ('game-3d-modeler-hardsurface', 'game-topology-uv', TRUE, 1.0),
    ('game-3d-modeler-hardsurface', 'game-pbr-texturing', TRUE, 1.0),
    ('game-3d-modeler-hardsurface', 'game-lods', TRUE, 1.0),
    ('game-3d-modeler-hardsurface', 'game-technical-art', FALSE, 1.0),
    ('game-3d-modeler-organic', 'game-3d-organic', TRUE, 1.0),
    ('game-3d-modeler-organic', 'game-topology-uv', TRUE, 1.0),
    ('game-3d-modeler-organic', 'game-pbr-texturing', TRUE, 1.0),
    ('game-3d-modeler-organic', 'game-lods', TRUE, 1.0),
    ('game-3d-modeler-organic', 'game-rigging', FALSE, 1.0),
    ('game-animator-2d', 'game-2d-animation', TRUE, 1.0),
    ('game-animator-2d', 'game-spine-rigging', TRUE, 1.0),
    ('game-animator-2d', 'game-anim-principles', TRUE, 1.0),
    ('game-animator-2d', 'game-vfx', FALSE, 1.0),
    ('game-animator-3d', 'game-3d-animation', TRUE, 1.0),
    ('game-animator-3d', 'game-anim-principles', TRUE, 1.0),
    ('game-animator-3d', 'game-facial-anim', TRUE, 1.0),
    ('game-animator-3d', 'game-rigging', FALSE, 1.0),
    ('game-vfx-artist', 'game-vfx', TRUE, 1.0),
    ('game-vfx-artist', 'game-frame-budget', TRUE, 1.0),
    ('game-vfx-artist', 'game-shaders', FALSE, 1.0),
    ('game-vfx-artist', 'game-anim-principles', FALSE, 1.0),
    ('game-technical-artist', 'game-technical-art', TRUE, 1.0),
    ('game-technical-artist', 'game-rigging', TRUE, 1.0),
    ('game-technical-artist', 'game-shaders', TRUE, 1.0),
    ('game-technical-artist', 'game-asset-pipeline', TRUE, 1.0),
    ('game-technical-artist', 'game-lods', TRUE, 1.0),
    ('game-modder', 'game-modding', TRUE, 1.0),
    ('game-modder', 'game-vendor-tos', TRUE, 1.0),
    ('game-modder', 'game-gameplay-systems', FALSE, 1.0),
    ('game-modder', 'game-playtesting', FALSE, 1.0),
    ('game-mapmaker', 'game-mapmaking', TRUE, 1.0),
    ('game-mapmaker', 'game-level-design', TRUE, 1.0),
    ('game-mapmaker', 'game-encounter-design', TRUE, 1.0),
    ('game-mapmaker', 'game-vendor-tos', TRUE, 1.0),
    ('game-mapmaker', 'game-playtesting', FALSE, 1.0),
    ('web3-game-dev', 'game-onchain', TRUE, 1.0),
    ('web3-game-dev', 'game-contract-audit', TRUE, 1.0),
    ('web3-game-dev', 'game-gameplay-systems', FALSE, 1.0),
    ('web3-game-dev', 'game-web-builds', FALSE, 1.0)
  ) AS v(orientation_slug, skill_slug, is_core, weight)
  JOIN orientations o ON o.slug = v.orientation_slug
  JOIN skill_nodes  s ON s.slug = v.skill_slug
ON CONFLICT (orientation_id, skill_id) DO NOTHING;

DO $$
DECLARE n INT;
BEGIN
    SELECT count(*) INTO n
      FROM orientation_skill_map m
      JOIN orientations o ON o.id = m.orientation_id
     WHERE o.primary_domain = 'game' AND o.slug LIKE 'game-%' OR o.slug = 'web3-game-dev';
    IF n < 111 THEN
        RAISE EXCEPTION 'expected 111 game skill-map edges, found %', n;
    END IF;
END $$;
