-- Which trade each seeded challenge belongs to, for the ten domains that knew
-- and did not write it down.
--
-- ## The gap, and why it is the one blocking everything
--
-- Migration 0606 gave `challenge_templates` an `orientation_id` and backfilled
-- the 130 design seeds. Every other domain's catalogue was left with NULL: 524
-- drafts across code, game, ops, security, ai, audio, quality, leadership,
-- communication and education.
--
-- That is not a tidiness problem. `POST /admin/orientations/{slug}/challenges/publish`
-- — the one surface that opens a catalogue, one trade at a time, gated on
-- `domain_curator:{domain}` — publishes `WHERE o.id = ct.orientation_id`. With
-- NULL everywhere but design, it publishes nothing for eleven domains of
-- twelve. So the platform stands at 654 drafts and, outside the twelve rites,
-- zero published challenges: a person finishes their first gesture and
-- `GET /api/challenges` hands them an empty list.
--
-- Opening a domain trade by trade is the plan; this is what makes it possible
-- to execute.
--
-- ## Where the pairs come from
--
-- Read back out of the seed migrations, the way 0606 read its 130 out of 0239
-- rather than retyping them. Every one of those migrations grouped its VALUES
-- by trade — it needed the trade to pick the review grid — and then discarded
-- it. `0185` (code), `0219` (ai), `0417`/`0423` (audio), `0425`/`0430`/`0432`
-- (ops), `0453`/`0459` (quality), `0465`/`0469` (leadership), `0512`/`0515`
-- (communication), `0528`/`0529` (education), `0558` (security), `0586` (game).
--
-- Verified before writing: the 524 pairs below match all 524 remaining drafts,
-- one to one, with no draft left over and no title ambiguous inside its
-- domain. Four further pairs the same extraction produced name a toolkit
-- rather than a challenge — a different VALUES block in 0459 and 0469 — and
-- match nothing; they are dropped rather than shipped as rows that update
-- nothing.
--
-- ## Why the key is sometimes a reviewer group
--
-- The security catalogue (0558) grouped by `reviewer_group` — `red-team`,
-- `blue-team`, `code-audit`, `governance`, `purple-team` — where the other
-- nine grouped by orientation slug. Each of those groups belongs to exactly
-- one security orientation, so the join accepts either, scoped to the
-- challenge's own domain so a group name shared between two domains cannot
-- cross over.
--
-- ## Matching on the title
--
-- Same reason 0606 gives: these migrations insert without returning anything,
-- so there is no id to have kept. No title repeats inside a domain — checked,
-- not assumed.

UPDATE challenge_templates ct
   SET orientation_id = o.id
  FROM (VALUES
    ('ai', 'data-engineer', 'Pipeline batch de bout en bout'),
    ('ai', 'data-engineer', 'Pipeline de flux temps réel'),
    ('ai', 'data-engineer', 'Migration d''entrepôt'),
    ('ai', 'data-engineer', 'Contrôles de qualité bloquants'),
    ('ai', 'data-engineer', 'Magasin de caractéristiques'),
    ('ai', 'data-analyst', 'Tableau de bord de six indicateurs'),
    ('ai', 'data-analyst', 'Analyse de cohortes'),
    ('ai', 'data-analyst', 'Analyse d''un test A/B'),
    ('ai', 'data-analyst', 'Rapport narratif'),
    ('ai', 'ml-engineer', 'Modèle de classification en production'),
    ('ai', 'ml-engineer', 'Système de recommandation'),
    ('ai', 'ml-engineer', 'Prévision de série temporelle'),
    ('ai', 'ml-engineer', 'Affinage d''un modèle pré-entraîné'),
    ('ai', 'ml-engineer', 'Déploiement fantôme'),
    ('ai', 'prompt-engineer', 'RAG sur un corpus documentaire'),
    ('ai', 'prompt-engineer', 'Bibliothèque de vingt invites'),
    ('ai', 'prompt-engineer', 'Agent conversationnel multi-tours'),
    ('ai', 'prompt-engineer', 'Défenses contre l''injection d''invite'),
    ('ai', 'llm-engineer', 'Affinage LoRA d''un modèle ouvert'),
    ('ai', 'llm-engineer', 'Recherche hybride avec reclassement'),
    ('ai', 'llm-engineer', 'Système multi-agents'),
    ('ai', 'llm-engineer', 'Agent à outils sous bac à sable'),
    ('ai', 'llm-engineer', 'Distillation vers un modèle plus petit'),
    ('ai', 'mlops-engineer', 'Service de modèle à l''échelle'),
    ('ai', 'mlops-engineer', 'Surveillance et dérive'),
    ('ai', 'mlops-engineer', 'Chaîne de réentraînement'),
    ('ai', 'mlops-engineer', 'Coût d''inférence divisé par deux'),
    ('ai', 'computer-vision-engineer', 'Détection d''objets déployée'),
    ('ai', 'computer-vision-engineer', 'Segmentation sémantique'),
    ('ai', 'computer-vision-engineer', 'Reconnaissance faciale et biais'),
    ('ai', 'computer-vision-engineer', 'Vision embarquée temps réel'),
    ('ai', 'nlp-engineer', 'Reconnaissance et liaison d''entités'),
    ('ai', 'nlp-engineer', 'Sentiment multilingue'),
    ('ai', 'nlp-engineer', 'Résumé abstractif'),
    ('ai', 'nlp-engineer', 'Traduction en langue peu dotée'),
    ('ai', 'ai-safety-researcher', 'Red-team d''un modèle ouvert'),
    ('ai', 'ai-safety-researcher', 'Évaluation de biais'),
    ('ai', 'ai-safety-researcher', 'Reproduction d''une technique d''alignement'),
    ('ai', 'generative-ai-artist', 'Chaîne de diffusion dirigée'),
    ('ai', 'generative-ai-artist', 'Graphe ComfyUI réutilisable'),
    ('ai', 'generative-ai-artist', 'Série cohérente de dix pièces'),
    ('audio', 'audio-composer', 'Thème principal de jeu — 90 secondes'),
    ('audio', 'audio-composer', 'Score narratif à l''image — 60 secondes'),
    ('audio', 'audio-composer', 'Jingle de marque et ses trois formats'),
    ('audio', 'audio-composer', 'Générique de podcast — entrée et sortie'),
    ('audio', 'audio-composer', 'Boucle d''ambiance de trois minutes'),
    ('audio', 'audio-composer', 'Bande originale de cinq morceaux'),
    ('audio', 'audio-music-implementer', 'Musique de combat adaptative — FMOD'),
    ('audio', 'audio-music-implementer', 'Remixage vertical à trois couches'),
    ('audio', 'audio-music-implementer', 'Reséquencement horizontal'),
    ('audio', 'audio-music-implementer', 'Ambiance adaptative — Wwise'),
    ('audio', 'audio-sound-designer', 'Pack d''interface de jeu — 15 sons'),
    ('audio', 'audio-sound-designer', 'Pack de combat — 20 sons'),
    ('audio', 'audio-sound-designer', 'Cinq ambiances distinctes'),
    ('audio', 'audio-sound-designer', 'Pack d''interface pour un produit — 10 sons'),
    ('audio', 'audio-sound-designer', 'Pack de bruitage — 30 sons'),
    ('audio', 'audio-voice-actor', 'Bande démo — 90 secondes'),
    ('audio', 'audio-voice-actor', 'Cinq personnages de jeu de rôle'),
    ('audio', 'audio-voice-actor', 'Narration de livre audio — 5 minutes'),
    ('audio', 'audio-voice-actor', 'Voix commerciale — 30 secondes'),
    ('audio', 'audio-voice-actor', 'Casting communautaire — audition et livraison'),
    ('audio', 'audio-programmer', 'Spatialisation binaurale dans un moteur'),
    ('audio', 'audio-programmer', 'Générateur de musique procédurale'),
    ('audio', 'audio-programmer', 'Greffon de traitement'),
    ('audio', 'audio-programmer', 'Enveloppe de middleware'),
    ('audio', 'audio-composer', 'Skilluv Coder Battle — thème principal'),
    ('audio', 'audio-composer', 'Skilluv Coder Battle — thème de fin de manche'),
    ('audio', 'audio-composer', 'Skilluv Craft Journey — bande originale en 5 morceaux'),
    ('audio', 'audio-composer', 'Skilluv — générique de la chaîne communautaire'),
    ('audio', 'audio-sound-designer', 'Skilluv — pack d''interface de la plateforme'),
    ('audio', 'audio-sound-designer', 'Skilluv — sons de progression et de rang'),
    ('audio', 'audio-sound-designer', 'Skilluv Coder Battle — pack de jeu'),
    ('audio', 'audio-voice-actor', 'Skilluv — voix du narrateur des jeux canvas'),
    ('audio', 'audio-voice-actor', 'Skilluv — voix d''accueil des nouveaux arrivants'),
    ('audio', 'audio-music-implementer', 'Skilluv Coder Battle — intégration musicale adaptative'),
    ('code', 'web-frontend-developer', 'Component library reusable'),
    ('code', 'web-frontend-developer', 'Performance refactor site'),
    ('code', 'web-frontend-developer', 'A11y audit + fixes complets'),
    ('code', 'web-frontend-developer', 'Progressive Web App'),
    ('code', 'web-frontend-developer', 'Micro-frontend architecture'),
    ('code', 'web-frontend-developer', 'State management library'),
    ('code', 'web-backend-developer', 'REST API + OpenAPI spec'),
    ('code', 'web-backend-developer', 'GraphQL schema + resolvers'),
    ('code', 'web-backend-developer', 'Authentication service'),
    ('code', 'web-backend-developer', 'Rate limiting + caching layer'),
    ('code', 'web-backend-developer', 'Webhook system + retry'),
    ('code', 'web-backend-developer', 'API versioning strategy'),
    ('code', 'web-fullstack-developer', 'SaaS mini app end-to-end'),
    ('code', 'web-fullstack-developer', 'Marketplace 2-sided app'),
    ('code', 'web-fullstack-developer', 'Real-time collab app'),
    ('code', 'web-fullstack-developer', 'E-commerce shop custom'),
    ('code', 'web-fullstack-developer', 'Blog platform custom'),
    ('code', 'web-performance-engineer', 'Perf audit + optimization'),
    ('code', 'web-performance-engineer', 'RUM setup + dashboard'),
    ('code', 'web-performance-engineer', 'Bundle size reduction ≥ 50%'),
    ('code', 'web-performance-engineer', 'Core Web Vitals passing'),
    ('code', 'web3-frontend-developer', 'dApp complet ethers.js'),
    ('code', 'web3-frontend-developer', 'Multi-wallet abstraction'),
    ('code', 'web3-frontend-developer', 'On-chain indexing frontend'),
    ('code', 'web3-frontend-developer', 'Account abstraction UX'),
    ('code', 'mobile-ios-developer', 'iOS app SwiftUI shipped'),
    ('code', 'mobile-ios-developer', 'HealthKit integration'),
    ('code', 'mobile-ios-developer', 'Widgets iOS 17+'),
    ('code', 'mobile-ios-developer', 'In-app purchase flow'),
    ('code', 'mobile-ios-developer', 'Push notifications rich'),
    ('code', 'mobile-android-developer', 'Android app Jetpack Compose shipped'),
    ('code', 'mobile-android-developer', 'Material 3 design system implementation'),
    ('code', 'mobile-android-developer', 'Background work WorkManager'),
    ('code', 'mobile-android-developer', 'Play Billing integration'),
    ('code', 'mobile-android-developer', 'Wear OS companion app'),
    ('code', 'mobile-cross-platform-developer', 'React Native app shipped'),
    ('code', 'mobile-cross-platform-developer', 'Flutter app shipped'),
    ('code', 'mobile-cross-platform-developer', 'Cross-platform native module'),
    ('code', 'mobile-cross-platform-developer', 'Offline-first architecture'),
    ('code', 'mobile-cross-platform-developer', 'Cross-platform DS component library'),
    ('code', 'desktop-app-developer', 'Tauri app shipped'),
    ('code', 'desktop-app-developer', 'Electron app shipped'),
    ('code', 'desktop-app-developer', 'Native Qt/GTK app'),
    ('code', 'desktop-app-developer', 'macOS AppKit app'),
    ('code', 'desktop-app-developer', '.NET WinUI 3 app'),
    ('code', 'enterprise-software-developer', 'SAP ABAP custom module'),
    ('code', 'enterprise-software-developer', 'Salesforce Apex + LWC'),
    ('code', 'enterprise-software-developer', 'ServiceNow scripted app'),
    ('code', 'enterprise-software-developer', 'Odoo custom module'),
    ('code', 'lowcode-platform-developer', 'Retool custom component published'),
    ('code', 'lowcode-platform-developer', 'n8n custom node published'),
    ('code', 'lowcode-platform-developer', 'Bubble plugin developed'),
    ('code', 'lowcode-platform-developer', 'Zapier custom app'),
    ('code', 'systems-programmer', 'Rust systems tool'),
    ('code', 'systems-programmer', 'C++ modern library'),
    ('code', 'systems-programmer', 'Zig systems experiment'),
    ('code', 'systems-programmer', 'Memory allocator custom'),
    ('code', 'systems-programmer', 'Async runtime custom'),
    ('code', 'systems-programmer', 'Bootloader custom'),
    ('code', 'kernel-driver-developer', 'Linux kernel patch merged'),
    ('code', 'kernel-driver-developer', 'Custom device driver'),
    ('code', 'kernel-driver-developer', 'eBPF program deployed'),
    ('code', 'kernel-driver-developer', 'Kernel module OSS'),
    ('code', 'kernel-driver-developer', 'Windows driver (WDM/WDF)'),
    ('code', 'firmware-embedded-developer', 'ESP32 IoT project shipped'),
    ('code', 'firmware-embedded-developer', 'STM32 RTOS project'),
    ('code', 'firmware-embedded-developer', 'Arduino library published'),
    ('code', 'firmware-embedded-developer', 'LoRaWAN device firmware'),
    ('code', 'firmware-embedded-developer', 'MQTT gateway custom'),
    ('code', 'firmware-embedded-developer', 'BLE peripheral firmware'),
    ('code', 'robotics-software-developer', 'ROS2 package published'),
    ('code', 'robotics-software-developer', 'Robot control custom'),
    ('code', 'robotics-software-developer', 'Drone autonomous flight'),
    ('code', 'robotics-software-developer', 'SLAM implementation'),
    ('code', 'safety-critical-developer', 'AUTOSAR module'),
    ('code', 'safety-critical-developer', 'DO-178C compliant subset'),
    ('code', 'safety-critical-developer', 'Medical device IEC 62304 module'),
    ('code', 'smart-contract-developer', 'ERC-20/721/1155 audited'),
    ('code', 'smart-contract-developer', 'DeFi primitive contract'),
    ('code', 'smart-contract-developer', 'DAO governance contract'),
    ('code', 'smart-contract-developer', 'NFT collection contract advanced'),
    ('code', 'smart-contract-developer', 'Cross-chain bridge contract'),
    ('code', 'blockchain-protocol-developer', 'L2 rollup contribution'),
    ('code', 'blockchain-protocol-developer', 'Consensus algorithm implementation'),
    ('code', 'blockchain-protocol-developer', 'ZK circuit implementation'),
    ('code', 'compiler-language-developer', 'Rust compiler PR merged'),
    ('code', 'compiler-language-developer', 'LLVM pass custom'),
    ('code', 'compiler-language-developer', 'Interpreter DSL'),
    ('code', 'compiler-language-developer', 'Custom linter'),
    ('code', 'formal-methods-developer', 'TLA+ specification'),
    ('code', 'formal-methods-developer', 'Coq/Lean proof'),
    ('code', 'formal-methods-developer', 'Property-based testing library'),
    ('code', 'database-engine-developer', 'PostgreSQL extension published'),
    ('code', 'database-engine-developer', 'PG contribution merged'),
    ('code', 'database-engine-developer', 'ClickHouse function custom'),
    ('code', 'database-engine-developer', 'Vector DB extension'),
    ('code', 'search-engine-developer', 'Elasticsearch plugin custom'),
    ('code', 'search-engine-developer', 'Meilisearch contribution'),
    ('code', 'search-engine-developer', 'Custom search engine (Tantivy/Sonic)'),
    ('code', 'distributed-systems-developer', 'Consensus implementation (Raft/etc)'),
    ('code', 'distributed-systems-developer', 'Message broker custom'),
    ('code', 'distributed-systems-developer', 'Distributed cache'),
    ('code', 'distributed-systems-developer', 'libp2p application'),
    ('code', 'stream-processing-developer', 'Kafka Streams application'),
    ('code', 'stream-processing-developer', 'Flink job production'),
    ('code', 'stream-processing-developer', 'Beam pipeline cross-runner'),
    ('code', 'scientific-computing-developer', 'NumPy/SciPy contribution'),
    ('code', 'scientific-computing-developer', 'Julia package published'),
    ('code', 'scientific-computing-developer', 'Bioinformatics tool'),
    ('code', 'scientific-computing-developer', 'Physics simulation'),
    ('code', 'gpu-compute-developer', 'CUDA kernel optimized'),
    ('code', 'gpu-compute-developer', 'WebGPU compute shader'),
    ('code', 'gpu-compute-developer', 'ROCm port CUDA library'),
    ('code', 'hft-quant-developer', 'Low-latency C++ trading engine minimal'),
    ('code', 'hft-quant-developer', 'Backtest framework Python'),
    ('code', 'hft-quant-developer', 'Risk model implementation'),
    ('code', 'network-protocol-developer', 'QUIC implementation minimal'),
    ('code', 'network-protocol-developer', 'Custom P2P protocol'),
    ('code', 'network-protocol-developer', 'Networking library published'),
    ('code', 'cli-tools-developer', 'CLI tool Rust/Go publié'),
    ('code', 'cli-tools-developer', 'TUI application'),
    ('code', 'cli-tools-developer', 'Developer productivity tool'),
    ('code', 'cli-tools-developer', 'CLI framework contribution'),
    ('code', 'cli-tools-developer', 'Shell scripting library'),
    ('code', 'ide-extension-developer', 'VSCode extension published'),
    ('code', 'ide-extension-developer', 'Neovim plugin (Lua)'),
    ('code', 'ide-extension-developer', 'JetBrains plugin'),
    ('code', 'ide-extension-developer', 'LSP server custom'),
    ('code', 'build-system-developer', 'Nix flake substantial'),
    ('code', 'build-system-developer', 'Bazel rules custom'),
    ('code', 'build-system-developer', 'Cargo/npm plugin'),
    ('code', 'media-processing-developer', 'FFmpeg contribution OR wrapper library'),
    ('code', 'media-processing-developer', 'OpenCV pipeline'),
    ('code', 'media-processing-developer', 'Custom codec implementation'),
    ('code', 'platform-app-developer', 'Discord bot serverless publié'),
    ('code', 'platform-app-developer', 'Slack app published + adopted'),
    ('code', 'platform-app-developer', 'Telegram bot production'),
    ('code', 'platform-app-developer', 'Browser extension shipped'),
    ('communication', 'tech-writer', 'Documentation contribution accepted upstream'),
    ('communication', 'tech-writer', 'Complete tutorial for one feature'),
    ('communication', 'tech-writer', 'Missing API reference'),
    ('communication', 'tech-writer', 'Changelog and migration guide'),
    ('communication', 'tech-writer', 'README rebuild for a community project'),
    ('communication', 'developer-advocate', 'A twenty-minute talk delivered'),
    ('communication', 'developer-advocate', 'Live demonstration'),
    ('communication', 'developer-advocate', 'Technical deep dive article'),
    ('communication', 'developer-advocate', 'A meetup organised end to end'),
    ('communication', 'content-creator-tech', 'Fifteen-minute video tutorial'),
    ('communication', 'content-creator-tech', 'Technical podcast episode'),
    ('communication', 'content-creator-tech', 'Four-hour development stream'),
    ('communication', 'content-creator-tech', 'A coherent series of three videos'),
    ('communication', 'technical-translator', 'Translating a section of open-source documentation'),
    ('communication', 'technical-translator', 'Translating the Skilluv interface'),
    ('communication', 'technical-translator', 'A coherent technical glossary'),
    ('communication', 'technical-translator', 'Improving a project''s i18n pipeline'),
    ('communication', 'research-writer-tech', 'Whitepaper on a technical subject'),
    ('communication', 'research-writer-tech', 'State of a technical sector'),
    ('communication', 'research-writer-tech', 'An external specification proposed'),
    ('communication', 'tech-writer', 'Skilluv — contributor getting-started guide'),
    ('communication', 'tech-writer', 'Skilluv — public API reference'),
    ('communication', 'tech-writer', 'Skilluv — explaining the proof model'),
    ('communication', 'tech-writer', 'Skilluv — release notes people can read'),
    ('communication', 'developer-advocate', 'Skilluv — a talk introducing the platform'),
    ('communication', 'developer-advocate', 'Skilluv — "my first contribution" workshop'),
    ('communication', 'content-creator-tech', 'Skilluv — video series on the contributor path'),
    ('communication', 'content-creator-tech', 'Skilluv — podcast episode with a member'),
    ('communication', 'technical-translator', 'Skilluv — interface in Portuguese and Arabic'),
    ('communication', 'research-writer-tech', 'Skilluv — the state of proving technical skill'),
    ('education', 'technical-trainer', 'A three-hour workshop, delivered'),
    ('education', 'technical-trainer', 'An eight-week cohort, end to end'),
    ('education', 'technical-trainer', 'Two days of training inside an organisation'),
    ('education', 'technical-trainer', 'A meetup with a hands-on half'),
    ('education', 'technical-trainer', 'A self-paced course in five modules'),
    ('education', 'curriculum-designer', 'A twelve-week bootcamp curriculum'),
    ('education', 'curriculum-designer', 'A learning path from junior to senior'),
    ('education', 'curriculum-designer', 'A skill matrix for a technical team'),
    ('education', 'curriculum-designer', 'An assessment framework'),
    ('education', 'coding-teacher', 'Ten lesson plans for absolute beginners'),
    ('education', 'coding-teacher', 'A term of teaching, with its outcomes'),
    ('education', 'coding-teacher', 'A turnaround, written up'),
    ('education', 'coding-teacher', 'A series on how people learn to program'),
    ('education', 'curriculum-designer', 'Skilluv — the first-contribution path'),
    ('education', 'curriculum-designer', 'Skilluv — Rust backend, an introduction'),
    ('education', 'curriculum-designer', 'Skilluv — reading a codebase you did not write'),
    ('education', 'technical-trainer', 'Skilluv — the first-contribution cohort'),
    ('education', 'technical-trainer', 'Skilluv — a workshop on the review grids'),
    ('education', 'technical-trainer', 'Skilluv — a workshop on writing a contribution'),
    ('education', 'coding-teacher', 'Skilluv — the beginner track, taught live'),
    ('education', 'coding-teacher', 'Skilluv — office hours, documented'),
    ('education', 'curriculum-designer', 'Skilluv — the reviewer''s programme'),
    ('education', 'technical-trainer', 'Skilluv — a train-the-trainer session'),
    ('game', 'game-gameplay-programmer', 'Third-person character controller'),
    ('game', 'game-gameplay-programmer', 'RPG inventory system'),
    ('game', 'game-gameplay-programmer', 'Branching dialogue system'),
    ('game', 'game-gameplay-programmer', 'Enemy behaviour tree'),
    ('game', 'game-gameplay-programmer', 'Multi-slot save system'),
    ('game', 'game-gameplay-programmer', 'Physics puzzle mechanic'),
    ('game', 'game-engine-programmer', 'Reusable Bevy plugin'),
    ('game', 'game-engine-programmer', 'Godot native extension'),
    ('game', 'game-engine-programmer', 'ECS from scratch'),
    ('game', 'game-engine-programmer', 'Memory profiling tool'),
    ('game', 'game-graphics-programmer', 'Stylised toon shader'),
    ('game', 'game-graphics-programmer', 'Realistic water shader'),
    ('game', 'game-graphics-programmer', 'Post-processing pipeline'),
    ('game', 'game-graphics-programmer', 'GPU particle system'),
    ('game', 'game-graphics-programmer', 'Custom lighting model'),
    ('game', 'game-network-programmer', 'Two-player peer-to-peer'),
    ('game', 'game-network-programmer', 'Authoritative server sync'),
    ('game', 'game-network-programmer', 'Rollback netcode'),
    ('game', 'game-network-programmer', 'Rank-based matchmaking'),
    ('game', 'game-ai-programmer', 'NPC crowd simulation'),
    ('game', 'game-ai-programmer', 'Utility AI system'),
    ('game', 'game-ai-programmer', 'Procedural dungeon generator'),
    ('game', 'game-ai-programmer', 'LLM-driven NPC'),
    ('game', 'game-tools-programmer', 'Godot editor plugin'),
    ('game', 'game-tools-programmer', 'Custom level editor'),
    ('game', 'game-tools-programmer', 'Asset pipeline automation'),
    ('game', 'game-tools-programmer', 'Localisation tool'),
    ('game', 'game-backend-programmer', 'Real-time leaderboard service'),
    ('game', 'game-backend-programmer', 'Achievement system backend'),
    ('game', 'game-backend-programmer', 'Cloud saves service'),
    ('game', 'game-backend-programmer', 'Live-ops event scheduler'),
    ('game', 'game-systems-designer', 'Full crafting system'),
    ('game', 'game-systems-designer', 'Combat balance across classes'),
    ('game', 'game-systems-designer', 'Ethical free-to-play progression'),
    ('game', 'game-systems-designer', 'Roguelike run structure'),
    ('game', 'game-systems-designer', 'Three multiplayer modes'),
    ('game', 'game-systems-designer', 'Balanced card game'),
    ('game', 'game-level-designer', 'Three-act platformer level'),
    ('game', 'game-level-designer', 'Metroidvania map'),
    ('game', 'game-level-designer', 'Multiplayer FPS arena'),
    ('game', 'game-level-designer', 'Puzzle level series'),
    ('game', 'game-level-designer', 'Open-world region'),
    ('game', 'game-narrative-designer', 'Three-act character arc'),
    ('game', 'game-narrative-designer', 'Compact worldbuilding'),
    ('game', 'game-narrative-designer', 'Branching quest'),
    ('game', 'game-narrative-designer', 'Environmental storytelling'),
    ('game', 'game-narrative-designer', 'Emergent narrative system'),
    ('game', 'game-economy-designer', 'Ethical free-to-play economy'),
    ('game', 'game-economy-designer', 'Dual-currency system'),
    ('game', 'game-economy-designer', 'MMORPG progression curve'),
    ('game', 'game-economy-designer', 'Battle-pass season'),
    ('game', 'game-combat-designer', 'Weight-heavy melee combat'),
    ('game', 'game-combat-designer', 'Eight-weapon arsenal'),
    ('game', 'game-combat-designer', 'Deep turn-based combat'),
    ('game', 'game-combat-designer', 'Three-phase boss'),
    ('game', 'game-3d-modeler-hardsurface', 'Sci-fi weapon pack'),
    ('game', 'game-3d-modeler-hardsurface', 'Drivable vehicle'),
    ('game', 'game-3d-modeler-hardsurface', 'Environment prop set'),
    ('game', 'game-3d-modeler-hardsurface', 'Modular building kit'),
    ('game', 'game-3d-modeler-hardsurface', 'Weapon customisation art'),
    ('game', 'game-3d-modeler-organic', 'Rig-ready hero character'),
    ('game', 'game-3d-modeler-organic', 'Stylised creature'),
    ('game', 'game-3d-modeler-organic', 'Character customisation set'),
    ('game', 'game-3d-modeler-organic', 'Character LOD pack'),
    ('game', 'game-3d-modeler-organic', 'Rig-ready biped animal'),
    ('game', 'game-animator-2d', 'Idle, run and attack'),
    ('game', 'game-animator-2d', 'Full sprite atlas'),
    ('game', 'game-animator-2d', 'Spine hero rig'),
    ('game', 'game-animator-2d', 'UI micro-animation pack'),
    ('game', 'game-animator-2d', 'Pixel-art VFX pack'),
    ('game', 'game-animator-3d', 'Locomotion pack'),
    ('game', 'game-animator-3d', 'Melee combat set'),
    ('game', 'game-animator-3d', 'Character reactions pack'),
    ('game', 'game-animator-3d', 'Cinematic cutscene'),
    ('game', 'game-animator-3d', 'Facial blendshapes'),
    ('game', 'game-vfx-artist', 'Combat impact VFX'),
    ('game', 'game-vfx-artist', 'Ambient environmental VFX'),
    ('game', 'game-vfx-artist', 'Elemental spell VFX'),
    ('game', 'game-vfx-artist', 'Weapon trail VFX'),
    ('game', 'game-vfx-artist', 'On-damage screen effects'),
    ('game', 'game-technical-artist', 'Shader-graph pipeline'),
    ('game', 'game-technical-artist', 'LOD auto-generation tool'),
    ('game', 'game-technical-artist', 'Texture optimisation pipeline'),
    ('game', 'game-technical-artist', 'Rigging templates library'),
    ('game', 'game-modder', 'Skyrim quality-of-life mod'),
    ('game', 'game-modder', 'Minecraft utility mod'),
    ('game', 'game-modder', 'Fallout 4 quest mod'),
    ('game', 'game-modder', '7 Days to Die overhaul'),
    ('game', 'game-modder', 'Cities: Skylines asset pack'),
    ('game', 'game-mapmaker', 'Fortnite Creative island'),
    ('game', 'game-mapmaker', 'Roblox experience'),
    ('game', 'game-mapmaker', 'Dreams creation'),
    ('game', 'game-mapmaker', 'Minecraft adventure map'),
    ('game', 'game-mapmaker', 'CS2 custom map'),
    ('game', 'web3-game-dev', 'NFT-gated content demo'),
    ('game', 'web3-game-dev', 'On-chain leaderboard'),
    ('game', 'web3-game-dev', 'Cross-game asset interop'),
    ('leadership', 'lead-product', 'A problem statement before a feature'),
    ('leadership', 'lead-product', 'A quarter, and what it costs'),
    ('leadership', 'lead-product', 'Five conversations, one synthesis'),
    ('leadership', 'lead-product', 'The feature that should be removed'),
    ('leadership', 'lead-product', 'Twelve months, three bets'),
    ('leadership', 'lead-tech', 'A decision, with its alternatives'),
    ('leadership', 'lead-tech', 'A migration with a state in between'),
    ('leadership', 'lead-tech', 'Scaling something that is not yet slow'),
    ('leadership', 'lead-tech', 'A post-incident decision record'),
    ('leadership', 'lead-tech', 'A direction for a team, in writing'),
    ('leadership', 'lead-project', 'An honest date'),
    ('leadership', 'lead-project', 'A risk register with responses'),
    ('leadership', 'lead-project', 'Coordinating four groups'),
    ('leadership', 'lead-project', 'The recovery plan'),
    ('leadership', 'lead-people', 'A ladder described by what people do'),
    ('leadership', 'lead-people', 'A hiring loop somebody can fail fairly'),
    ('leadership', 'lead-people', 'One-to-ones that are not status updates'),
    ('leadership', 'lead-people', 'Asking a team what it thinks'),
    ('leadership', 'lead-community', 'Who it is for, and who it is not'),
    ('leadership', 'lead-community', 'A programme that runs on people'),
    ('leadership', 'lead-community', 'The moderation rules, written before the incident'),
    ('leadership', 'lead-community', 'Six months of content, aimed at something'),
    ('leadership', 'lead-mentor', 'A curriculum with an entry condition'),
    ('leadership', 'lead-mentor', 'The first ninety days'),
    ('leadership', 'lead-mentor', 'A cohort, run to the end'),
    ('leadership', 'lead-mentor', 'What happened to the people'),
    ('leadership', 'lead-mentor', 'Skilluv cohort lead'),
    ('leadership', 'lead-community', 'Skilluv community operations'),
    ('leadership', 'lead-product', 'Skilluv roadmap contributor'),
    ('ops', 'devops-engineer', 'Un pipeline depuis rien'),
    ('ops', 'devops-engineer', 'Sortir les secrets du dépôt'),
    ('ops', 'devops-engineer', 'Un module qui s''applique deux fois'),
    ('ops', 'devops-engineer', 'Un retour en arrière qui marche'),
    ('ops', 'sre', 'Un premier objectif de service'),
    ('ops', 'sre', 'Une politique de budget d''erreur'),
    ('ops', 'sre', 'Le runbook du pire cas'),
    ('ops', 'sre', 'Une journée de panne organisée'),
    ('ops', 'cloud-architect', 'Une architecture chiffrée'),
    ('ops', 'cloud-architect', 'Nommer l''enfermement'),
    ('ops', 'cloud-architect', 'Une reprise testée'),
    ('ops', 'cloud-architect', 'Le choix de la région'),
    ('ops', 'platform-engineer', 'Un chemin par défaut'),
    ('ops', 'platform-engineer', 'Un environnement en libre-service'),
    ('ops', 'platform-engineer', 'La documentation du chemin'),
    ('ops', 'platform-engineer', 'Mesurer la friction'),
    ('ops', 'kubernetes-specialist', 'Un premier opérateur'),
    ('ops', 'kubernetes-specialist', 'Un chart qui se met à jour'),
    ('ops', 'kubernetes-specialist', 'GitOps depuis zéro'),
    ('ops', 'kubernetes-specialist', 'Des limites qui tiennent'),
    ('ops', 'observability-engineer', 'Trois questions, deux minutes'),
    ('ops', 'observability-engineer', 'Une alerte qui mérite de réveiller'),
    ('ops', 'observability-engineer', 'Une trace de bout en bout'),
    ('ops', 'observability-engineer', 'La facture de la cardinalité'),
    ('ops', 'incident-commander', 'Conduire un exercice'),
    ('ops', 'incident-commander', 'Un post-mortem sans blâme'),
    ('ops', 'incident-commander', 'Communiquer pendant'),
    ('ops', 'database-administrator', 'Une migration sans verrou'),
    ('ops', 'database-administrator', 'Un index qui se justifie'),
    ('ops', 'database-administrator', 'Restaurer pour de vrai'),
    ('ops', 'database-administrator', 'Le décalage de réplication'),
    ('ops', 'devops-engineer', 'Le pipeline de Skilluv, plus court d''un tiers'),
    ('ops', 'devops-engineer', 'Une image de conteneur plus petite'),
    ('ops', 'kubernetes-specialist', 'Les manifestes de Skilluv'),
    ('ops', 'kubernetes-specialist', 'Des limites justifiées par une mesure'),
    ('ops', 'observability-engineer', 'Le tableau de bord de Skilluv'),
    ('ops', 'observability-engineer', 'Les alertes qui méritent de réveiller'),
    ('ops', 'observability-engineer', 'Suivre une requête de bout en bout'),
    ('ops', 'database-administrator', 'Les requêtes les plus coûteuses de Skilluv'),
    ('ops', 'database-administrator', 'Une sauvegarde restaurée pour de vrai'),
    ('ops', 'sre', 'Le premier objectif de service de Skilluv'),
    ('ops', 'devops-engineer', 'Sortir un secret de notre historique'),
    ('ops', 'platform-engineer', 'Le chemin le plus court pour contribuer'),
    ('ops', 'devops-engineer', 'Une image dix fois plus petite'),
    ('ops', 'devops-engineer', 'Une chaîne de livraison qui refuse de livrer'),
    ('ops', 'sre', 'Une astreinte tenable'),
    ('ops', 'sre', 'Un test de charge et ce qu''il révèle'),
    ('ops', 'cloud-architect', 'Un tiers de facture en moins'),
    ('ops', 'cloud-architect', 'Une architecture sans serveur, chiffrée honnêtement'),
    ('ops', 'platform-engineer', 'Les quatre chiffres de DORA'),
    ('ops', 'platform-engineer', 'Un environnement de développement reproductible'),
    ('ops', 'kubernetes-specialist', 'Un maillage de services et ce qu''il coûte'),
    ('ops', 'kubernetes-specialist', 'Une montée de version sans coupure'),
    ('ops', 'observability-engineer', 'Des journaux qui ne coûtent pas une fortune'),
    ('ops', 'observability-engineer', 'Une lenteur trouvée par la trace'),
    ('ops', 'incident-commander', 'Un manuel de réponse complet'),
    ('ops', 'incident-commander', 'Animer un post-mortem'),
    ('ops', 'database-administrator', 'Une bascule jouée pour de vrai'),
    ('ops', 'database-administrator', 'Un entrepôt analytique qui répond en une seconde'),
    ('quality', 'qa-code', 'A test plan before the feature'),
    ('quality', 'qa-code', 'The test that would pass anyway'),
    ('quality', 'qa-code', 'An end-to-end suite on a real journey'),
    ('quality', 'qa-code', 'A coverage figure that says where the holes are'),
    ('quality', 'qa-code', 'Tests that search instead of waiting'),
    ('quality', 'qa-cyber', 'A replayable report on a training target'),
    ('quality', 'qa-cyber', 'A security test plan for an API'),
    ('quality', 'qa-cyber', 'A scanner in the pipeline, without the noise'),
    ('quality', 'qa-cyber', 'A static analysis rule for an in-house defect'),
    ('quality', 'qa-design', 'Five sessions, one protocol'),
    ('quality', 'qa-design', 'An accessibility audit against a named standard'),
    ('quality', 'qa-design', 'The gap between the mockup and what shipped'),
    ('quality', 'qa-design', 'Where people give up'),
    ('quality', 'qa-game', 'Five sessions on a jam game'),
    ('quality', 'qa-game', 'A balance analysis that comes with its volume'),
    ('quality', 'qa-game', 'Four hours without a script'),
    ('quality', 'qa-game', 'A protocol for one genre'),
    ('quality', 'qa-game', 'Playing against the rules, with permission'),
    ('quality', 'qa-lead', 'What a team tests, and what it gives up testing'),
    ('quality', 'qa-lead', 'An initiative that survives its launch'),
    ('quality', 'qa-lead', 'The handbook of a team growing fast'),
    ('quality', 'qa-code', 'A failing test for an open Skilluv issue'),
    ('quality', 'qa-code', 'A test plan for a Skilluv feature under discussion'),
    ('quality', 'qa-design', 'An accessibility audit of one Skilluv page'),
    ('quality', 'qa-design', 'A usability study of the Skilluv onboarding'),
    ('quality', 'qa-game', 'Sessions on a Skilluv canvas game'),
    ('quality', 'qa-lead', 'Read our test strategy back to us'),
    ('security', 'red-team', 'Juice Shop — log in as the administrator'),
    ('security', 'red-team', 'Juice Shop — find the score board'),
    ('security', 'red-team', 'Juice Shop — make it leak a stack trace'),
    ('security', 'red-team', 'Juice Shop — log in as another customer'),
    ('security', 'red-team', 'Juice Shop — change a password without the old one'),
    ('security', 'red-team', 'Juice Shop — reflected cross-site scripting'),
    ('security', 'red-team', 'Juice Shop — cross-site scripting in the page itself'),
    ('security', 'red-team', 'Juice Shop — stored cross-site scripting'),
    ('security', 'red-team', 'Juice Shop — act on behalf of a logged-in user'),
    ('security', 'red-team', 'Juice Shop — read a file you were not offered'),
    ('security', 'red-team', 'Juice Shop — read somebody else''s basket'),
    ('security', 'red-team', 'Juice Shop — undo the "encryption"'),
    ('security', 'red-team', 'Juice Shop — forge a session token'),
    ('security', 'red-team', 'Juice Shop — buy something for the wrong price'),
    ('security', 'red-team', 'Juice Shop — get the list of every customer address'),
    ('security', 'red-team', 'Juice Shop — upload something that should have been refused'),
    ('security', 'red-team', 'Juice Shop — make the server fetch a URL for you'),
    ('security', 'red-team', 'Juice Shop — run code on the server'),
    ('security', 'red-team', 'Juice Shop — recover a password from its hash'),
    ('security', 'red-team', 'Juice Shop — chain three defects into one impact'),
    ('security', 'code-audit', 'WebGoat — one defect class, end to end'),
    ('security', 'red-team', 'DVWA — the same defect at four difficulty levels'),
    ('security', 'red-team', 'PortSwigger Academy — one topic, all its labs'),
    ('security', 'code-audit', 'Audit this platform''s authentication'),
    ('security', 'code-audit', 'Audit this platform''s authorisation'),
    ('security', 'code-audit', 'Audit this platform''s file handling'),
    ('security', 'governance', 'Audit this platform''s privacy documentation'),
    ('security', 'governance', 'Audit this platform''s threat model'),
    ('security', 'red-team', 'VulnHub — an easy machine, written up'),
    ('security', 'red-team', 'VulnHub — a medium machine, written up'),
    ('security', 'red-team', 'HackTheBox — a retired easy machine, written up'),
    ('security', 'red-team', 'HackTheBox — a retired medium machine, written up'),
    ('security', 'red-team', 'HackTheBox — a retired hard machine, written up'),
    ('security', 'blue-team', 'TryHackMe — a defensive path, written up'),
    ('security', 'blue-team', 'A brute-force attempt in a web server log'),
    ('security', 'blue-team', 'A password in cleartext on the wire'),
    ('security', 'blue-team', 'Which account was compromised, and when'),
    ('security', 'blue-team', 'Data leaving over DNS'),
    ('security', 'blue-team', 'Credential theft in a memory image'),
    ('security', 'blue-team', 'A web shell in a server log'),
    ('security', 'blue-team', 'Triage a day of intrusion detection alerts'),
    ('security', 'blue-team', 'A command-and-control channel hiding in normal traffic'),
    ('security', 'blue-team', 'Triage a suspicious file without running it'),
    ('security', 'blue-team', 'One incident, three sources, one timeline'),
    ('security', 'purple-team', 'Run a technique, then prove you can see it'),
    ('security', 'purple-team', 'Five techniques, and an honest coverage statement')
  ) AS v(skill_domain, trade_key, title)
  JOIN orientations o
    ON o.primary_domain = v.skill_domain
   AND (o.slug = v.trade_key OR o.reviewer_group = v.trade_key)
 WHERE ct.skill_domain = v.skill_domain
   AND ct.title = v.title
   AND ct.orientation_id IS NULL;

COMMENT ON COLUMN challenge_templates.orientation_id IS
    'The trade this challenge belongs to, when it belongs to one. NULL for a '
    'challenge that is the domain''s rather than one trade''s — the twelve '
    'Bonjour Skilluv rites, and the per-starter variants of the code one. '
    'Backfilled for design by migration 0606 and for the other ten catalogues '
    'by 0612; it is what '
    'POST /admin/orientations/{slug}/challenges/publish selects on, so a NULL '
    'here is a challenge no curator can open.';
