//! A message a person reads does not carry a run of spaces.
//!
//! Rust string literals written across source lines keep every space of the
//! indentation unless the line ends in a backslash. Thirty-three of ours had
//! lost theirs, so an operator opening the logs read
//!
//! ```text
//! similarity sweep failed - triagers will be reading without                      duplicate candidates
//! ```
//!
//! and somebody disabling two-factor authentication was answered with the
//! same gap in the middle of the sentence. Nothing was broken by it, which is
//! exactly why it survived: it is invisible in the source, where the
//! indentation looks like indentation.
//!
//! The check is a test for the same reason `no_em_dashes` is one: this
//! repository runs its tests on every change, and a hook is advice while a
//! red check is an answer.

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::Path;
    use std::process::Command;

    /// Three, not two.
    ///
    /// Two spaces after a full stop is a typographic choice somebody may
    /// hold. Three or more inside a sentence is never one: it is indentation
    /// that escaped into the string.
    const RUN: &str = "   ";

    /// Where a run of spaces is the subject rather than an accident.
    ///
    /// Console output that lines up columns, and fixtures whose runs of
    /// spaces are the input a normaliser is asked to flatten. Collapsing
    /// those changes what the code means, and each was found by reading a
    /// diff that had already changed them.
    ///
    /// Short, because trimming the literal first removed the need for most of
    /// it: tests and comments about blank input are no longer matched at all.
    const EXEMPT: &[&str] = &[
        // Console output that lines up two columns.
        "src/bin/seed_admin.rs",
        // Fixtures whose runs of spaces are what the function under test is
        // asked to normalise.
        "src/services/fedapay.rs",
        "src/services/mentions.rs",
        // A Python fixture, where the indentation is the language.
        "tests/suite/test_e2e_ai_grpc.rs",
        // This file quotes an offending line to explain itself.
        "src/no_collapsed_continuations.rs",
    ];

    fn tracked_rust_files(root: &Path) -> Vec<String> {
        let out = Command::new("git")
            .arg("ls-files")
            .current_dir(root)
            .output()
            .expect("git ls-files: this guard needs a git checkout to know what it covers");
        assert!(out.status.success(), "git ls-files failed");
        String::from_utf8_lossy(&out.stdout)
            .lines()
            .map(|l| l.trim().to_string())
            .filter(|l| l.ends_with(".rs"))
            // The tests too. An assertion message is read by somebody who is
            // already debugging, which is the worst moment to hand them a
            // sentence with a hole in it.
            .filter(|l| l.starts_with("src/") || l.starts_with("tests/"))
            // Generated by prost from the proto files, and not ours to format.
            .filter(|l| !l.starts_with("src/grpc/generated/"))
            .filter(|l| !EXEMPT.contains(&l.as_str()))
            .collect()
    }

    /// SQL ignores whitespace, so a run inside a query is not a defect.
    ///
    /// Embedded queries are indented to stay readable and that indentation
    /// reaches the string exactly the same way. The difference is that
    /// nobody reads it.
    fn looks_like_sql(line: &str) -> bool {
        const KEYWORDS: &[&str] = &[
            "SELECT",
            "INSERT",
            "UPDATE",
            "DELETE",
            "FROM",
            "WHERE",
            "JOIN",
            "ORDER BY",
            "GROUP BY",
            "VALUES",
            "RETURNING",
            "COALESCE",
            "CREATE",
            "ALTER",
        ];
        KEYWORDS.iter().any(|k| line.contains(k))
    }

    /// Every run of spaces that sits between two quotes on one line.
    ///
    /// Scanning inside the quotes rather than across the line is what keeps
    /// aligned attribute tables out of it: their padding is between the
    /// literals, not inside them.
    fn offending_spans(line: &str) -> Vec<String> {
        let mut found = Vec::new();
        let mut in_str = false;
        let mut escaped = false;
        let mut buf = String::new();
        for c in line.chars() {
            if escaped {
                escaped = false;
                if in_str {
                    buf.push(c);
                }
                continue;
            }
            match c {
                '\\' if in_str => escaped = true,
                '"' => {
                    if in_str {
                        // Trimmed first: a literal made only of spaces is a
                        // deliberate blank, not a lost continuation. Half the
                        // matches were tests asserting that whitespace-only
                        // input is refused, where the spaces are the subject.
                        // Trailing padding goes the same way.
                        if buf.trim().contains(RUN) {
                            found.push(buf.trim().chars().take(70).collect::<String>());
                        }
                        buf.clear();
                    }
                    in_str = !in_str;
                }
                _ if in_str => buf.push(c),
                _ => {}
            }
        }
        found
    }

    #[test]
    fn no_message_carries_a_lost_line_continuation() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let mut offenders = Vec::new();

        for rel in tracked_rust_files(root) {
            let Ok(text) = fs::read_to_string(root.join(&rel)) else {
                continue;
            };
            for (n, line) in text.lines().enumerate() {
                // A raw string is quoted differently and is normally SQL or a
                // regex; neither is prose.
                if line.contains("r#\"") || looks_like_sql(line) {
                    continue;
                }
                for span in offending_spans(line) {
                    offenders.push(format!("{rel}:{}: {span}", n + 1));
                }
            }
        }

        assert!(
            offenders.is_empty(),
            "these string literals carry a run of spaces, which is almost always \
             a multi-line literal missing its trailing backslash:\n  {}",
            offenders.join("\n  ")
        );
    }

    /// The exemption list names files that exist.
    ///
    /// An exemption for a file somebody has since renamed is an exemption
    /// that silently covers nothing, and this guard would then be one file
    /// weaker than it reads.
    #[test]
    fn every_exemption_still_points_at_a_file() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        for rel in EXEMPT {
            assert!(
                root.join(rel).exists(),
                "{rel} is exempted and does not exist"
            );
        }
    }
}
