//! OpenAPI 3.1 schema generation (BE-P1-CONTRACT).
//!
//! Root `ApiDoc` derive collects every handler annotated with
//! `#[utoipa::path(...)]` across the codebase and every DTO annotated with
//! `#[derive(ToSchema)]`. The schema is exposed at :
//!
//!   - `GET  /api/openapi.json`  — raw JSON (consumed by schemathesis in CI)
//!   - `GET  /api/docs`          — Swagger UI (interactive exploration)
//!
//! Contract testing lives in `.github/workflows/contract-test.yml` — it
//! boots the API against a real Postgres, fetches `/api/openapi.json` and
//! runs schemathesis property-based fuzzing to catch payload contract
//! drifts between backend and front.
//!
//! ## How to add a handler
//!
//! 1. Put `#[utoipa::path(...)]` on the handler function.
//! 2. Ensure every request/response struct derives `utoipa::ToSchema`.
//! 3. Register the handler in `paths(...)` and any bespoke DTOs in
//!    `components(schemas(...))` below.
//! 4. `cargo check` — the derive will yell about anything missing.
//!
//! Shared envelope types (`ApiResponse<T>`, `ErrorResponse`) live in
//! `crate::api_response` and are pre-registered here.

use axum::{Router, response::IntoResponse};
use utoipa::{
    Modify, OpenApi,
    openapi::security::{ApiKey, ApiKeyValue, HttpAuthScheme, HttpBuilder, SecurityScheme},
};
use utoipa_swagger_ui::SwaggerUi;

use crate::api_response::{ApiResponse, ErrorObject, ErrorResponse, MetaInfo, SimpleMessage};

/// Root OpenAPI document. Every route module contributes its own set of
/// `#[utoipa::path]` handlers here via the `paths(...)` and `components(...)`
/// arguments. Kept intentionally short — the real work happens in the
/// per-handler annotations spread across `src/routes/`.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Skilluv Backend API",
        description = "Compétences tech prouvées par des artefacts opposables. \
                       Contract-tested via schemathesis on every PR.",
        contact(name = "Skilluv Team", email = "security@skilluv.com"),
        license(name = "Proprietary"),
    ),
    servers(
        (url = "/api", description = "Same-origin (typical Coolify deploy)"),
        (url = "http://localhost:3001/api", description = "Local dev"),
    ),
    modifiers(&SecurityAddon),
    paths(
        // ─── auth ─────────────────────────────────────────────────
        crate::routes::auth::verify_email,
        crate::routes::auth::resend_verification,
        crate::routes::auth::forgot_password,
        crate::routes::auth::reset_password,
        crate::routes::auth::change_password,
        crate::routes::auth::logout,
        crate::routes::auth::list_sessions,
        crate::routes::auth::revoke_session,
        crate::routes::auth::revoke_all_other_sessions,
        crate::routes::auth::totp_disable,
        crate::routes::auth::email_2fa_enable,
        crate::routes::auth::email_2fa_disable,
        crate::routes::auth::me,
        crate::routes::auth::request_email_change,
        crate::routes::auth::confirm_email_change,
        crate::routes::auth::refresh,
        crate::routes::auth::complete_profile,
        crate::routes::auth::totp_setup,
        crate::routes::auth::totp_enable,
        crate::routes::auth::regenerate_backup_codes,
        crate::routes::auth::delete_account,
        crate::routes::auth::request_data_export,
        crate::routes::auth::register,
        crate::routes::auth::login,
        crate::routes::auth::email_2fa_verify,
        // ─── health ───────────────────────────────────────────────
        crate::routes::health::liveness,
        crate::routes::health::deep_health,
        // ─── magic link ───────────────────────────────────────────
        crate::routes::magic_link::request_link,
        crate::routes::magic_link::consume_link,
        // ─── geo ──────────────────────────────────────────────────
        crate::routes::geo::list_countries,
        crate::routes::geo::search_cities,
        // ─── i18n ─────────────────────────────────────────────────
        crate::routes::i18n::list_locales,
        // ─── email preferences ────────────────────────────────────
        crate::routes::email_prefs::get_prefs,
        crate::routes::email_prefs::update_prefs,
        crate::routes::email_prefs::unsubscribe,
        crate::routes::email_prefs::brevo_webhook,
        crate::routes::email_prefs::admin_run_weekly_digest,
        // ─── metrics (internal dashboards) ────────────────────────
        crate::routes::metrics::metrics_summary,
        // ─── tracks ───────────────────────────────────────────────
        crate::routes::tracks::list_tracks,
        crate::routes::tracks::get_track,
        crate::routes::tracks::enroll_track,
        crate::routes::tracks::track_progress,
        crate::routes::tracks::my_tracks,
        crate::routes::tracks::challenge_eligibility,
        // ─── notifications ────────────────────────────────────────
        crate::routes::notifications::list_notifications,
        crate::routes::notifications::mark_read,
        crate::routes::notifications::mark_all_read,
        crate::routes::notifications::unread_count,
        // ─── legal / consent ──────────────────────────────────────
        crate::routes::legal::consent_version,
        crate::routes::legal::record_consent,
        // ─── badges ───────────────────────────────────────────────
        crate::routes::badges::user_badges,
        crate::routes::badges::list_rules,
        // ─── reports (user-facing moderation) ─────────────────────
        crate::routes::reports::create_report,
        crate::routes::reports::my_reports,
        crate::routes::reports::cancel_report,
        // ─── capabilities ─────────────────────────────────────────
        crate::routes::capabilities::user_capabilities_public,
        crate::routes::capabilities::my_capabilities,
        crate::routes::capabilities::admin_grant_capability,
        crate::routes::capabilities::admin_revoke_capability,
        // ─── portfolio ────────────────────────────────────────────
        crate::routes::portfolio::portfolio_json,
        crate::routes::portfolio::badge_svg,
        // ─── events (badge-events) ────────────────────────────────
        crate::routes::events::list_events,
        crate::routes::events::join_event,
        crate::routes::events::my_events,
        // ─── skills ───────────────────────────────────────────────
        crate::routes::skills::list_skills,
        crate::routes::skills::find_talents,
        crate::routes::skills::user_skills,
        crate::routes::skills::my_skill_recommendations,
        // ─── ai jobs ──────────────────────────────────────────────
        crate::routes::ai_jobs::request_code_review,
        crate::routes::ai_jobs::request_recommendations,
        crate::routes::ai_jobs::get_job_result,
        crate::routes::ai_jobs::admin_hidden_gems,
        crate::routes::ai_jobs::admin_churn,
        // ─── attestations ─────────────────────────────────────────
        crate::routes::attestations::list_user_attestations,
        crate::routes::attestations::verify_attestation,
        crate::routes::attestations::issue_compagnonnage,
        crate::routes::attestations::revoke_attestation,
        // ─── push notifications ───────────────────────────────────
        crate::routes::push::vapid_public_key,
        crate::routes::push::subscribe,
        crate::routes::push::unsubscribe,
        crate::routes::push::register_mobile_token,
        crate::routes::push::revoke_mobile_token,
        crate::routes::push::list_mobile_tokens,
        // ─── seasons + stewards ───────────────────────────────────
        crate::routes::seasons::list_seasons,
        crate::routes::seasons::current_season,
        crate::routes::seasons::get_season,
        crate::routes::seasons::create_season,
        crate::routes::seasons::activate_season,
        crate::routes::seasons::list_project_stewards,
        crate::routes::seasons::add_steward,
        crate::routes::seasons::remove_steward,
        crate::routes::seasons::my_stewardships,
        // ─── agency_clients + type_config ─────────────────────────
        crate::routes::agency_clients::get_type_config,
        crate::routes::agency_clients::patch_type_config,
        crate::routes::agency_clients::list,
        crate::routes::agency_clients::create,
        crate::routes::agency_clients::update,
        crate::routes::agency_clients::deactivate,
        // ─── ai coach ─────────────────────────────────────────────
        crate::routes::ai_coach::my_performance,
        crate::routes::ai_coach::suggest_orientations,
        // ─── certifications + diplomas ────────────────────────────
        crate::routes::certifications::list_certifications,
        crate::routes::certifications::purchase_certification,
        crate::routes::certifications::start_attempt,
        crate::routes::certifications::submit_attempt,
        crate::routes::certifications::verify_diploma,
        crate::routes::certifications::my_diplomas,
        // ─── leaderboard ──────────────────────────────────────────
        crate::routes::leaderboard::list_leaderboards,
        crate::routes::leaderboard::get_leaderboard,
        crate::routes::leaderboard::my_rank,
        // ─── legal well-known (enterprise dashboard + accounting) ─
        crate::routes::legal_well_known::admin_accounting_export,
        crate::routes::legal_well_known::dashboard_overview,
        crate::routes::legal_well_known::dashboard_funnel,
        // ─── sponsored challenges ─────────────────────────────────
        crate::routes::sponsored_challenges::request_sponsorship,
        crate::routes::sponsored_challenges::list_my_requests,
        crate::routes::sponsored_challenges::admin_list_requests,
        crate::routes::sponsored_challenges::admin_decide_request,
        crate::routes::sponsored_challenges::admin_link_challenge,
        crate::routes::sponsored_challenges::public_active,
        crate::routes::sponsored_challenges::sponsor_view_submissions,
        // ─── orientations ─────────────────────────────────────────
        crate::routes::orientations::list_orientations,
        crate::routes::orientations::get_orientation,
        crate::routes::orientations::my_orientations,
        crate::routes::orientations::register_orientation,
        crate::routes::orientations::update_orientation,
        crate::routes::orientations::orientation_playlist,
        crate::routes::orientations::end_orientation,
        crate::routes::orientations::public_user_orientations,
        // ─── talent lists + bookmarks ─────────────────────────────
        crate::routes::talent_lists::add_bookmark,
        crate::routes::talent_lists::remove_bookmark,
        crate::routes::talent_lists::list_bookmarks,
        crate::routes::talent_lists::create_list,
        crate::routes::talent_lists::list_lists,
        crate::routes::talent_lists::get_list,
        crate::routes::talent_lists::update_list,
        crate::routes::talent_lists::delete_list,
        crate::routes::talent_lists::add_to_list,
        crate::routes::talent_lists::remove_from_list,
        // ─── tenants (white-label) ────────────────────────────────
        crate::routes::tenants::get_current_tenant,
        crate::routes::tenants::list_tenants,
        crate::routes::tenants::create_tenant,
        crate::routes::tenants::get_tenant,
        crate::routes::tenants::update_tenant,
        crate::routes::tenants::list_members,
        crate::routes::tenants::add_member,
        crate::routes::tenants::list_cohorts,
        crate::routes::tenants::create_cohort,
        // ─── onboarding (Bonjour Skilluv) ─────────────────────────
        crate::routes::onboarding::start_bonjour_skilluv,
        crate::routes::onboarding::get_bonjour_skilluv_status,
        // ─── challenge tags + featured ────────────────────────────
        crate::routes::challenge_tags::list_tags,
        crate::routes::challenge_tags::list_categories,
        crate::routes::challenge_tags::featured_challenges,
        // ─── sandbox (Judge0) ─────────────────────────────────────
        crate::routes::sandbox::execute,
        crate::routes::sandbox::execute_async,
        crate::routes::sandbox::get_result,
        crate::routes::sandbox::list_languages,
        // ─── admin content ops ────────────────────────────────────
        crate::routes::admin_content_ops::hello_wall_mirror_run,
        crate::routes::admin_content_ops::profile_readme_sync_run,
        crate::routes::admin_content_ops::recompute_badges_for_user,
        // ─── enterprise subscriptions ─────────────────────────────
        crate::routes::enterprise_subscriptions::subscribe_to_pipeline,
        crate::routes::enterprise_subscriptions::current_subscription,
        crate::routes::enterprise_subscriptions::cancel_subscription,
        // ─── enterprise dashboard stats ───────────────────────────
        crate::routes::enterprise_dashboard::platform_stats,
        crate::routes::enterprise_dashboard::my_stats,
        // ─── gamification (skill tree + heatmap) ──────────────────
        crate::routes::gamification::my_skill_tree,
        crate::routes::gamification::user_skill_tree,
        crate::routes::gamification::my_heatmap,
        crate::routes::gamification::user_heatmap,
        // ─── public API v1 ────────────────────────────────────────
        crate::routes::public_api::get_user_profile,
        crate::routes::public_api::get_user_badges,
        crate::routes::public_api::get_user_skills,
        // ─── review queue ─────────────────────────────────────────
        crate::routes::review_queue::list_open,
        crate::routes::review_queue::get_task,
        crate::routes::review_queue::claim_task,
        crate::routes::review_queue::submit_review,
        crate::routes::review_queue::list_reviews,
        // ─── talent search v3 ─────────────────────────────────────
        crate::routes::talent_search_v3::search_v3,
        // ─── explore feed ─────────────────────────────────────────
        crate::routes::explore::explore,
        // ─── admin dashboard ──────────────────────────────────────
        crate::routes::admin_dashboard::overview,
        crate::routes::admin_dashboard::financial,
        crate::routes::admin_dashboard::moderation_queue,
        crate::routes::admin_dashboard::ops_health,
        // ─── admin community (challenge review) ───────────────────
        crate::routes::admin_community::pending_review,
        crate::routes::admin_community::approve_challenge,
        crate::routes::admin_community::reject_challenge,
        // ─── DM ───────────────────────────────────────────────────
        crate::routes::dm::open_conversation,
        crate::routes::dm::list_conversations,
        crate::routes::dm::list_messages,
        crate::routes::dm::send_message,
        crate::routes::dm::mark_read,
        crate::routes::dm::block_user,
        crate::routes::dm::unblock_user,
        crate::routes::dm::list_blocks,
        // ─── talent search (v1 + v2) ──────────────────────────────
        crate::routes::talent_search::search_talents,
        crate::routes::talent_search::talent_card,
        crate::routes::talent_search_v2::search_v2,
        // ─── forum ────────────────────────────────────────────────
        crate::routes::forum::list_categories,
        crate::routes::forum::list_posts,
        crate::routes::forum::create_post,
        crate::routes::forum::get_post,
        crate::routes::forum::edit_post,
        crate::routes::forum::delete_post,
        crate::routes::forum::accept_answer,
        crate::routes::forum::toggle_pin,
        crate::routes::forum::toggle_lock,
        crate::routes::forum::search,
        // ─── admin users ──────────────────────────────────────────
        crate::routes::admin_users::admin_recompute_proofs,
        crate::routes::admin_users::admin_rank_override,
        // ─── projects ─────────────────────────────────────────────
        crate::routes::projects::create_project,
        crate::routes::projects::list_looking,
        crate::routes::projects::list_curated,
        crate::routes::projects::by_slug,
        crate::routes::projects::by_user,
        crate::routes::projects::by_guild_slug,
        crate::routes::projects::list_contributors,
        crate::routes::projects::add_contributor,
        crate::routes::projects::remove_contributor,
        crate::routes::projects::archive,
        crate::routes::projects::admin_set_curated,
        crate::routes::projects::my_project_recommendations,
        crate::routes::projects::mark_projects_interested,
        crate::routes::projects::list_my_project_interests,
        crate::routes::projects::unmark_project_interested,
        // ─── feed ─────────────────────────────────────────────────
        crate::routes::feed::my_feed,
        crate::routes::feed::for_you_feed,
        // ─── community challenges ─────────────────────────────────
        crate::routes::community::create_community_challenge,
        crate::routes::community::my_challenges,
        crate::routes::community::update_community_challenge,
        crate::routes::community::vote_challenge,
        crate::routes::community::unvote_challenge,
        crate::routes::community::popular_challenges,
        // ─── deliverables ─────────────────────────────────────────
        crate::routes::deliverables::get_deliverable,
        crate::routes::deliverables::list_user_deliverables,
        crate::routes::deliverables::github_slices_webhook,
        // ─── slices ───────────────────────────────────────────────
        crate::routes::slices::list_open,
        crate::routes::slices::get_slice,
        crate::routes::slices::claim_slice,
        crate::routes::slices::unclaim_slice,
        crate::routes::slices::my_slices,
        crate::routes::slices::claim_slice_as_team,
        crate::routes::slices::unclaim_slice_by_team,
        crate::routes::slices::team_slices,
        crate::routes::slices::steward_inbox,
        crate::routes::slices::publish_slice,
        crate::routes::slices::reject_slice,
        // ─── enterprise pipeline (kanban) ─────────────────────────
        crate::routes::enterprise_pipeline::list_entries,
        crate::routes::enterprise_pipeline::add_entry,
        crate::routes::enterprise_pipeline::update_entry,
        crate::routes::enterprise_pipeline::remove_entry,
        crate::routes::enterprise_pipeline::export_csv,
        // ─── moderation (inline non-admin) ────────────────────────
        crate::routes::moderation::community_review_queue,
        crate::routes::moderation::community_challenge_approve,
        crate::routes::moderation::community_challenge_reject,
        crate::routes::moderation::fraud_flagged_list,
        crate::routes::moderation::fraud_mark_valid,
        crate::routes::moderation::fraud_revoke,
        crate::routes::moderation::forum_moderate_post,
        crate::routes::moderation::forum_mute_user,
        // ─── tournament ───────────────────────────────────────────
        crate::routes::tournament::admin_create_season,
        crate::routes::tournament::admin_set_season_status,
        crate::routes::tournament::admin_close_season,
        crate::routes::tournament::list_tournaments,
        crate::routes::tournament::get_tournament,
        crate::routes::tournament::get_leaderboard,
        crate::routes::tournament::register,
        crate::routes::tournament::admin_create_tournament,
        crate::routes::tournament::admin_set_tournament_status,
        crate::routes::tournament::admin_set_score,
        crate::routes::tournament::admin_conclude,
        crate::routes::tournament::events_feed,
        // ─── profile (rank history + public profile) ──────────────
        crate::routes::profile::user_rank_history,
        crate::routes::profile::public_profile,
        // ─── user_profile (me settings) ───────────────────────────
        crate::routes::user_profile::update_profile,
        crate::routes::user_profile::upload_avatar,
        crate::routes::user_profile::delete_avatar,
        crate::routes::user_profile::get_privacy,
        crate::routes::user_profile::update_privacy,
        crate::routes::user_profile::update_display_name,
        crate::routes::user_profile::update_skill_domain,
        // ─── profile_extras (experiences, edu, langs) ─────────────
        crate::routes::profile_extras::get_availability,
        crate::routes::profile_extras::update_availability,
        crate::routes::profile_extras::list_experiences,
        crate::routes::profile_extras::add_experience,
        crate::routes::profile_extras::update_experience,
        crate::routes::profile_extras::delete_experience,
        crate::routes::profile_extras::list_educations,
        crate::routes::profile_extras::add_education,
        crate::routes::profile_extras::update_education,
        crate::routes::profile_extras::delete_education,
        crate::routes::profile_extras::list_languages,
        crate::routes::profile_extras::set_language,
        crate::routes::profile_extras::remove_language,
        crate::routes::profile_extras::clear_languages,
        // ─── social (comments, reactions, mentions, tags) ─────────
        crate::routes::social::create_comment,
        crate::routes::social::list_comments,
        crate::routes::social::edit_comment,
        crate::routes::social::delete_comment,
        crate::routes::social::toggle_reaction,
        crate::routes::social::reaction_summary,
        crate::routes::social::my_mentions,
        crate::routes::social::list_tags,
        crate::routes::social::list_target_tags,
        crate::routes::social::attach_tag,
        crate::routes::social::detach_tag,
        crate::routes::social::admin_create_tag,
        // ─── webauthn ─────────────────────────────────────────────
        crate::routes::webauthn::register_start,
        crate::routes::webauthn::register_finish,
        crate::routes::webauthn::list_credentials,
        crate::routes::webauthn::rename_credential,
        crate::routes::webauthn::delete_credential,
        crate::routes::webauthn::login_start,
        crate::routes::webauthn::login_finish,
        // ─── github integration ───────────────────────────────────
        crate::routes::github::start,
        crate::routes::github::callback,
        crate::routes::github::disconnect,
        crate::routes::github::sync_now,
        crate::routes::github::admin_sync,
        crate::routes::github::public_repos,
        crate::routes::github::cv_html,
        // ─── developer (API keys + webhooks) ──────────────────────
        crate::routes::developer::create_key,
        crate::routes::developer::list_keys,
        crate::routes::developer::revoke_key,
        crate::routes::developer::regenerate_key,
        crate::routes::developer::key_usage,
        crate::routes::developer::create_webhook,
        crate::routes::developer::list_webhooks,
        crate::routes::developer::update_webhook,
        crate::routes::developer::delete_webhook,
        crate::routes::developer::test_webhook,
        // ─── bounties (OSS) ───────────────────────────────────────
        crate::routes::bounties::list_bounties,
        crate::routes::bounties::get_bounty,
        crate::routes::bounties::create_bounty,
        crate::routes::bounties::claim_bounty,
        crate::routes::bounties::submit_pr,
        crate::routes::bounties::cancel_bounty,
        crate::routes::bounties::github_webhook,
        // ─── admin ops ────────────────────────────────────────────
        crate::routes::admin_ops::admin_sweep_proof_hooks,
        crate::routes::admin_ops::admin_trigger_gdpr_export,
        crate::routes::admin_ops::admin_recompute_capabilities,
        crate::routes::admin_ops::admin_list_badge_events,
        crate::routes::admin_ops::admin_create_badge_event,
        // ─── admin orientations ──────────────────────────────────
        crate::routes::admin_orientations::create_orientation,
        crate::routes::admin_orientations::patch_orientation,
        crate::routes::admin_orientations::attach_skill,
        crate::routes::admin_orientations::detach_skill,
        // ─── admin skills ────────────────────────────────────────
        crate::routes::admin_skills::list_skills,
        crate::routes::admin_skills::create_skill,
        crate::routes::admin_skills::update_skill,
        // ─── admin enterprises ───────────────────────────────────
        crate::routes::admin_enterprises::list_enterprises,
        crate::routes::admin_enterprises::get_enterprise,
        crate::routes::admin_enterprises::patch_type,
        crate::routes::admin_enterprises::get_type_config,
        crate::routes::admin_enterprises::list_agency_clients,
        // ─── admin badge rules ───────────────────────────────────
        crate::routes::admin_badge_rules::create_rule,
        crate::routes::admin_badge_rules::patch_rule,
        crate::routes::admin_badge_rules::deprecate_rule,
        // ─── admin fraud ─────────────────────────────────────────
        crate::routes::admin_fraud::fraud_queue,
        crate::routes::admin_fraud::mark_deliverable_valid,
        crate::routes::admin_fraud::revoke_deliverable,
        crate::routes::admin_fraud::mark_user_valid,
        crate::routes::admin_fraud::scan_deliverable_endpoint,
        crate::routes::admin_fraud::detect_multi_accounts_endpoint,
        crate::routes::admin_fraud::llm_evaluate_endpoint,
        crate::routes::admin_fraud::deep_plagiarism_scan_endpoint,
        // ─── oauth ───────────────────────────────────────────────
        crate::routes::oauth::list_my_providers,
        crate::routes::oauth::unlink_provider,
        crate::routes::oauth::google_start,
        crate::routes::oauth::google_link_start,
        crate::routes::oauth::google_callback,
        crate::routes::oauth::linkedin_start,
        crate::routes::oauth::linkedin_link_start,
        crate::routes::oauth::linkedin_callback,
        crate::routes::oauth::github_login_start,
        crate::routes::oauth::github_login_callback,
        // ─── scim ────────────────────────────────────────────────
        crate::routes::scim::create_scim_token,
        crate::routes::scim::revoke_scim_token,
        crate::routes::scim::set_group_role_mapping,
        crate::routes::scim::sp_config,
        crate::routes::scim::resource_types,
        crate::routes::scim::schemas,
        crate::routes::scim::list_users,
        crate::routes::scim::create_user,
        crate::routes::scim::get_user,
        crate::routes::scim::replace_user,
        crate::routes::scim::patch_user,
        crate::routes::scim::delete_user,
        crate::routes::scim::create_group,
        crate::routes::scim::list_groups,
        crate::routes::scim::get_group,
        crate::routes::scim::replace_group,
        crate::routes::scim::patch_group,
        crate::routes::scim::delete_group,
        // ─── admin (challenges CRUD + audit + SSO sessions + 2fa reset) ─
        crate::routes::admin::admin_reset_2fa,
        crate::routes::admin::list_audit_log,
        crate::routes::admin::create_challenge,
        crate::routes::admin::list_all_challenges,
        crate::routes::admin::update_challenge,
        crate::routes::admin::publish_challenge,
        crate::routes::admin::archive_challenge,
        crate::routes::admin::admin_stats,
        crate::routes::admin::rebuild_leaderboards,
        crate::routes::admin::list_sso_sessions,
        crate::routes::admin::revoke_sso_session,
        crate::routes::admin::admin_generate_variant,
        // ─── admin moderation ────────────────────────────────────
        crate::routes::admin_moderation::list_users,
        crate::routes::admin_moderation::get_user,
        crate::routes::admin_moderation::ban_user,
        crate::routes::admin_moderation::unban_user,
        crate::routes::admin_moderation::list_reports,
        crate::routes::admin_moderation::handle_report,
        crate::routes::admin_moderation::audit_log,
        crate::routes::admin_moderation::moderation_dashboard,
        // ─── admin projects ──────────────────────────────────────
        crate::routes::admin_projects::create_project,
        crate::routes::admin_projects::list_projects,
        crate::routes::admin_projects::get_project,
        crate::routes::admin_projects::patch_project,
        crate::routes::admin_projects::archive_project,
        // ─── contact (interest + conversations) ──────────────────
        crate::routes::contact::send_interest,
        crate::routes::contact::sent_requests,
        crate::routes::contact::received_requests,
        crate::routes::contact::accept_interest,
        crate::routes::contact::decline_interest,
        crate::routes::contact::list_conversations,
        crate::routes::contact::get_conversation,
        crate::routes::contact::send_message,
        crate::routes::contact::block_enterprise,
        crate::routes::contact::unblock_enterprise,
        // ─── enterprise KYC ──────────────────────────────────────
        crate::routes::enterprise_kyc::get_status,
        crate::routes::enterprise_kyc::upload_document,
        crate::routes::enterprise_kyc::admin_list,
        crate::routes::enterprise_kyc::admin_decide,
        // ─── enterprise SSO ──────────────────────────────────────
        crate::routes::enterprise_sso::upsert_config,
        crate::routes::enterprise_sso::get_config,
        crate::routes::enterprise_sso::disable_config,
        crate::routes::enterprise_sso::discover,
        crate::routes::enterprise_sso::start,
        crate::routes::enterprise_sso::callback,
        // ─── challenges ──────────────────────────────────────────
        crate::routes::challenges::get_challenge,
        crate::routes::challenges::get_onboarding,
        crate::routes::challenges::list_challenges,
        crate::routes::challenges::my_submissions,
        crate::routes::challenges::start_challenge,
        crate::routes::challenges::submit_challenge,
        // ─── challenge teams ─────────────────────────────────────
        crate::routes::challenge_teams::attach_team_to_guild,
        crate::routes::challenge_teams::create_persistent_team,
        crate::routes::challenge_teams::create_team,
        crate::routes::challenge_teams::create_team_slot,
        crate::routes::challenge_teams::delete_team_slot,
        crate::routes::challenge_teams::detach_team_from_guild,
        crate::routes::challenge_teams::disband_team,
        crate::routes::challenge_teams::extend_timer,
        crate::routes::challenge_teams::fill_team_slot,
        crate::routes::challenge_teams::get_team,
        crate::routes::challenge_teams::get_timer,
        crate::routes::challenge_teams::join_persistent_team,
        crate::routes::challenge_teams::join_team,
        crate::routes::challenge_teams::leave_team_slot,
        crate::routes::challenge_teams::list_open_slots_by_role,
        crate::routes::challenge_teams::list_team_slots,
        crate::routes::challenge_teams::list_teams,
        crate::routes::challenge_teams::marketplace_slots,
        crate::routes::challenge_teams::my_teams,
        crate::routes::challenge_teams::submit_team,
        // ─── enterprise ──────────────────────────────────────────
        crate::routes::enterprise::accept_invite,
        crate::routes::enterprise::delete_logo,
        crate::routes::enterprise::get_profile,
        crate::routes::enterprise::invite_preview,
        crate::routes::enterprise::invite_recruiter,
        crate::routes::enterprise::invite_register_and_accept,
        crate::routes::enterprise::list_members,
        crate::routes::enterprise::list_memberships,
        crate::routes::enterprise::register_enterprise,
        crate::routes::enterprise::revoke_member,
        crate::routes::enterprise::switch_enterprise,
        crate::routes::enterprise::update_profile,
        crate::routes::enterprise::upload_logo,
        // ─── enterprise credits ──────────────────────────────────
        crate::routes::enterprise_credits::billing_portal,
        crate::routes::enterprise_credits::create_checkout,
        crate::routes::enterprise_credits::get_credits,
        crate::routes::enterprise_credits::get_invoice,
        crate::routes::enterprise_credits::get_invoice_html,
        crate::routes::enterprise_credits::list_invoices,
        crate::routes::enterprise_credits::list_txns,
        crate::routes::enterprise_credits::public_pricing,
        crate::routes::enterprise_credits::redeem_promo,
        crate::routes::enterprise_credits::stripe_webhook,
        // ─── guild ───────────────────────────────────────────────
        crate::routes::guild::accept_invite,
        crate::routes::guild::admin_dissolve,
        crate::routes::guild::apply,
        crate::routes::guild::conclude_war,
        crate::routes::guild::create_guild,
        crate::routes::guild::create_token_link,
        crate::routes::guild::decide_application,
        crate::routes::guild::get_by_slug,
        crate::routes::guild::guild_composition,
        crate::routes::guild::invite_direct,
        crate::routes::guild::join_by_token,
        crate::routes::guild::kick_member,
        crate::routes::guild::leave_guild,
        crate::routes::guild::list_applications,
        crate::routes::guild::list_for_leaderboard,
        crate::routes::guild::list_invitations,
        crate::routes::guild::list_members,
        crate::routes::guild::list_wars,
        crate::routes::guild::promote_member,
        crate::routes::guild::propose_war,
        crate::routes::guild::respond_war,
        // ─── mentorship ──────────────────────────────────────────
        crate::routes::mentorship::add_availability,
        crate::routes::mentorship::book_session,
        crate::routes::mentorship::cancel_session,
        crate::routes::mentorship::connect_status,
        crate::routes::mentorship::get_mentor_profile,
        crate::routes::mentorship::get_my_mentor_profile,
        crate::routes::mentorship::list_mentors,
        crate::routes::mentorship::list_my_sessions,
        crate::routes::mentorship::mark_completed,
        crate::routes::mentorship::start_connect_onboarding,
        crate::routes::mentorship::submit_review,
        crate::routes::mentorship::upsert_my_mentor_profile,
        // ─── talent wallet ───────────────────────────────────────
        crate::routes::talent_wallet::momo_withdraw,
        crate::routes::talent_wallet::my_wallet,
        crate::routes::talent_wallet::my_wallet_transactions,
        crate::routes::talent_wallet::register_momo_phone,
        crate::routes::talent_wallet::set_my_residency,
        crate::routes::talent_wallet::stripe_connect_webhook,
        crate::routes::talent_wallet::stripe_onboard,
        crate::routes::talent_wallet::stripe_withdraw,
        crate::routes::talent_wallet::wallet_statement_csv,
    ),
    components(
        schemas(
            ErrorResponse,
            ErrorObject,
            MetaInfo,
            SimpleMessage,
            ApiResponse<SimpleMessage>,
            crate::routes::auth::ForgotPasswordRequest,
            crate::routes::auth::VerifyEmailQuery,
            crate::routes::auth::ResetPasswordRequest,
            crate::routes::auth::ChangePasswordRequest,
            crate::routes::auth::ListSessionsResponse,
            crate::services::session::SessionRow,
            crate::routes::auth::TotpDisableRequest,
            crate::routes::auth::PasswordConfirmRequest,
            crate::routes::auth::MeResponse,
            crate::routes::auth::RankInfo,
            crate::models::UserPrivate,
            crate::routes::auth::ChangeEmailRequest,
            crate::routes::auth::ConfirmEmailChangeQuery,
            crate::routes::auth::RefreshResponse,
            crate::routes::auth::CompleteProfileRequest,
            crate::routes::auth::CompleteProfileResponse,
            crate::routes::auth::TotpCodeRequest,
            crate::routes::auth::TotpSetupResponse,
            crate::routes::auth::TotpEnableResponse,
            crate::routes::auth::DeleteAccountRequest,
            crate::routes::auth::DeleteAccountResponse,
            crate::routes::auth::DataExportResponse,
            crate::routes::auth::RegisterRequest,
            crate::routes::auth::RegisterResponse,
            crate::routes::auth::LoginRequest,
            crate::routes::auth::LoginSuccessResponse,
            crate::routes::auth::LoginPending2faResponse,
            crate::routes::auth::LoginOutcome,
            crate::routes::auth::Email2faVerifyRequest,
            crate::routes::health::LivenessResponse,
            crate::routes::health::DeepHealthResponse,
            crate::routes::health::HealthServices,
            crate::routes::health::ServiceHealth,
            crate::routes::health::WebsocketStats,
            crate::routes::magic_link::MagicLinkRequestBody,
            crate::routes::magic_link::MagicLinkRequestResponse,
            crate::routes::magic_link::MagicLinkConsumeBody,
            crate::routes::magic_link::MagicLinkConsumeResponse,
            crate::routes::geo::CityOut,
            crate::services::geo::Country,
            crate::routes::i18n::LocalesResponse,
            crate::routes::i18n::LocaleEntry,
            crate::routes::email_prefs::EmailPrefs,
            crate::routes::email_prefs::EmailPrefsResponse,
            crate::routes::email_prefs::UpdatePrefsRequest,
            crate::routes::email_prefs::AdminDigestResponse,
            crate::services::digest::DigestRunReport,
            crate::routes::metrics::MetricsSummary,
            crate::routes::metrics::UsersStats,
            crate::routes::metrics::ChallengesStats,
            crate::routes::metrics::ModerationStats,
            crate::routes::metrics::MessagingStats,
            crate::routes::metrics::MetricsWebsocketStats,
            crate::routes::metrics::DatabasePoolStats,
            crate::services::tracks::Track,
            crate::services::tracks::UserTrack,
            crate::services::tracks::TrackProgress,
            crate::services::tracks::EligibilityCheck,
            crate::routes::tracks::TracksListResponse,
            crate::routes::tracks::TrackDetailResponse,
            crate::routes::tracks::EnrollResponse,
            crate::routes::tracks::TrackProgressResponse,
            crate::routes::tracks::MyTrackEntry,
            crate::routes::tracks::MyTracksResponse,
            crate::routes::tracks::EligibilityResponse,
            crate::models::Notification,
            crate::routes::notifications::Pagination,
            crate::routes::notifications::NotificationsListResponse,
            crate::routes::notifications::UnreadCountResponse,
            crate::routes::legal::LegalPages,
            crate::routes::legal::ConsentVersionResponse,
            crate::routes::legal::ConsentBody,
            crate::routes::legal::ConsentRecordedResponse,
            crate::routes::badges::BadgeItem,
            crate::routes::badges::RankRow,
            crate::routes::badges::UserBadgesResponse,
            crate::routes::badges::RuleCatalogRow,
            crate::routes::badges::RulesCatalogResponse,
            crate::routes::reports::CreateReportRequest,
            crate::routes::reports::Report,
            crate::routes::reports::CreateReportResponse,
            crate::routes::reports::MyReportsResponse,
            crate::routes::capabilities::CapabilityRow,
            crate::routes::capabilities::UserCapabilitiesResponse,
            crate::routes::capabilities::GrantBody,
            crate::routes::capabilities::CapabilityGrantResponse,
            crate::routes::capabilities::CapabilityRevokeResponse,
            // events
            crate::routes::events::EventRow,
            crate::routes::events::EventsListResponse,
            crate::routes::events::JoinEventResponse,
            crate::routes::events::MyEventRow,
            crate::routes::events::MyEventsResponse,
            // skills
            crate::models::SkillNode,
            crate::services::skills::UserSkillEnriched,
            crate::services::skills::SkillTalent,
            crate::services::skills::SliceRecommendation,
            crate::services::skills::RecommendationSkillMatch,
            crate::routes::skills::SkillsListResponse,
            crate::routes::skills::SkillTalentsResponse,
            crate::routes::skills::UserSkillsResponse,
            crate::routes::skills::SkillRecommendationsResponse,
            // ai jobs
            crate::routes::ai_jobs::CodeReviewBody,
            crate::routes::ai_jobs::AiJobEnqueuedResponse,
            crate::routes::ai_jobs::AiJobResultResponse,
            // attestations
            crate::services::attestations::Attestation,
            crate::routes::attestations::UserAttestationsResponse,
            crate::routes::attestations::AttestationVerifyResponse,
            crate::routes::attestations::CompagnonnageBody,
            crate::routes::attestations::IssueAttestationResponse,
            crate::routes::attestations::RevokeBody,
            crate::routes::attestations::RevokeAttestationResponse,
            // push
            crate::routes::push::VapidPublicKeyResponse,
            crate::routes::push::SubscribeBody,
            crate::routes::push::SubscribeResponse,
            crate::routes::push::UnsubscribeResponse,
            crate::routes::push::RegisterMobileTokenBody,
            crate::routes::push::MobileTokenRegisteredResponse,
            crate::routes::push::MobileTokenRevokedResponse,
            crate::routes::push::MobileTokenSummary,
            crate::routes::push::MobileTokensListResponse,
            // seasons + stewards
            crate::services::seasons::Season,
            crate::services::stewards::ProjectSteward,
            crate::routes::seasons::SeasonsListResponse,
            crate::routes::seasons::SeasonResponse,
            crate::routes::seasons::CurrentSeasonResponse,
            crate::routes::seasons::CreateSeasonBody,
            crate::routes::seasons::StewardsListResponse,
            crate::routes::seasons::StewardResponse,
            crate::routes::seasons::AddStewardBody,
            crate::routes::seasons::StewardshipsResponse,
            // agency_clients
            crate::routes::agency_clients::TypeConfigResponse,
            crate::routes::agency_clients::TypeConfigUpdatedResponse,
            crate::routes::agency_clients::AgencyClientRow,
            crate::routes::agency_clients::AgencyClientsListResponse,
            crate::routes::agency_clients::CreateBody,
            crate::routes::agency_clients::AgencyClientCreatedResponse,
            crate::routes::agency_clients::UpdateBody,
            crate::routes::agency_clients::AgencyClientUpdatedResponse,
            crate::routes::agency_clients::AgencyClientDeactivatedResponse,
            // ai coach
            crate::routes::ai_coach::AiCoachEnvelope,
            crate::routes::ai_coach::SuggestBody,
            // certifications
            crate::routes::certifications::CertificationRow,
            crate::routes::certifications::CertificationsListResponse,
            crate::routes::certifications::PurchaseResponse,
            crate::routes::certifications::StartAttemptResponse,
            crate::routes::certifications::SubmitAttemptResponse,
            crate::routes::certifications::DiplomaHolder,
            crate::routes::certifications::DiplomaCertification,
            crate::routes::certifications::VerifyDiplomaResponse,
            crate::routes::certifications::MyDiplomaRow,
            crate::routes::certifications::MyDiplomasResponse,
            // leaderboard
            crate::routes::leaderboard::LeaderboardMeta,
            crate::routes::leaderboard::LeaderboardsIndexResponse,
            crate::routes::leaderboard::LeaderboardEntry,
            crate::routes::leaderboard::LeaderboardPage,
            crate::routes::leaderboard::LeaderboardPageResponse,
            crate::routes::leaderboard::MyRankResponse,
            // legal_well_known
            crate::routes::legal_well_known::DashboardCredits,
            crate::routes::legal_well_known::DashboardInterestRequests,
            crate::routes::legal_well_known::DashboardOverviewResponse,
            crate::routes::legal_well_known::DashboardFunnel,
            crate::routes::legal_well_known::DashboardFunnelResponse,
            // sponsored challenges
            crate::routes::sponsored_challenges::RequestBody,
            crate::routes::sponsored_challenges::RequestCreatedResponse,
            crate::routes::sponsored_challenges::SponsorshipRequestRow,
            crate::routes::sponsored_challenges::MyRequestsResponse,
            crate::routes::sponsored_challenges::AdminSponsorshipRow,
            crate::routes::sponsored_challenges::AdminRequestsResponse,
            crate::routes::sponsored_challenges::DecideBody,
            crate::routes::sponsored_challenges::DecideResponse,
            crate::routes::sponsored_challenges::LinkChallengeBody,
            crate::routes::sponsored_challenges::LinkChallengeResponse,
            crate::routes::sponsored_challenges::ActiveSponsoredRow,
            crate::routes::sponsored_challenges::ActiveSponsoredResponse,
            crate::routes::sponsored_challenges::SponsorSubmissionRow,
            crate::routes::sponsored_challenges::SponsorSubmissionsResponse,
            // orientations
            crate::routes::orientations::OrientationRow,
            crate::routes::orientations::CatalogPagination,
            crate::routes::orientations::OrientationsCatalogResponse,
            crate::routes::orientations::OrientationSkillEntry,
            crate::routes::orientations::OrientationDetailResponse,
            crate::routes::orientations::UserOrientationRow,
            crate::routes::orientations::MyOrientationsResponse,
            crate::routes::orientations::RegisterBody,
            crate::routes::orientations::RegisterOrientationResponse,
            crate::routes::orientations::UpdateBody,
            crate::routes::orientations::UpdateOrientationResponse,
            crate::routes::orientations::EndOrientationResponse,
            crate::routes::orientations::PublicUserOrientationRow,
            crate::routes::orientations::PublicUserOrientationsResponse,
            // talent lists
            crate::models::TalentList,
            crate::routes::talent_lists::CreateListRequest,
            crate::routes::talent_lists::UpdateListRequest,
            crate::routes::talent_lists::BookmarkedTalent,
            crate::routes::talent_lists::BookmarksPageResponse,
            crate::routes::talent_lists::ListResponse,
            crate::routes::talent_lists::TalentListSummary,
            crate::routes::talent_lists::ListsResponse,
            crate::routes::talent_lists::ListMemberTalent,
            crate::routes::talent_lists::ListDetailResponse,
            // tenants
            crate::routes::tenants::PublicTenant,
            crate::routes::tenants::AdminTenant,
            crate::routes::tenants::AdminTenantSummary,
            crate::routes::tenants::TenantsListResponse,
            crate::routes::tenants::CreateTenantBody,
            crate::routes::tenants::TenantCreatedResponse,
            crate::routes::tenants::UpdateTenantBody,
            crate::routes::tenants::TenantUpdatedResponse,
            crate::routes::tenants::TenantMemberRow,
            crate::routes::tenants::MembersResponse,
            crate::routes::tenants::AddMemberBody,
            crate::routes::tenants::MemberAddedResponse,
            crate::routes::tenants::CohortRow,
            crate::routes::tenants::CohortsResponse,
            crate::routes::tenants::CreateCohortBody,
            crate::routes::tenants::CohortCreatedResponse,
            // onboarding
            crate::routes::onboarding::OnboardingProgress,
            crate::routes::onboarding::StartNextSteps,
            crate::routes::onboarding::StartBonjourResponse,
            crate::routes::onboarding::StatusBonjourResponse,
            // challenge tags
            crate::models::ChallengeTemplate,
            crate::routes::challenge_tags::TagWithCount,
            crate::routes::challenge_tags::TagsResponse,
            crate::routes::challenge_tags::CategoryRow,
            crate::routes::challenge_tags::CategoriesResponse,
            crate::routes::challenge_tags::FeaturedChallengesResponse,
            // sandbox
            crate::services::sandbox::LanguageInfo,
            crate::services::sandbox::ExecutionResult,
            crate::services::sandbox::ExecutionStatus,
            crate::routes::sandbox::ExecuteRequest,
            crate::routes::sandbox::ExecuteResponse,
            crate::routes::sandbox::AsyncExecuteResponse,
            crate::routes::sandbox::AsyncResultResponse,
            crate::routes::sandbox::LanguagesResponse,
            // admin content ops
            crate::routes::admin_content_ops::MirrorFailedDetail,
            crate::routes::admin_content_ops::HelloWallMirrorReport,
            crate::routes::admin_content_ops::ProfileReadmeSyncReport,
            crate::routes::admin_content_ops::BadgeRecomputeReport,
            // enterprise subscriptions
            crate::routes::enterprise_subscriptions::SubscribeBody,
            crate::routes::enterprise_subscriptions::SubscribeResponse,
            crate::routes::enterprise_subscriptions::SubscriptionDetail,
            crate::routes::enterprise_subscriptions::CurrentSubscriptionResponse,
            crate::routes::enterprise_subscriptions::CancelSubscriptionResponse,
            // enterprise dashboard
            crate::routes::enterprise_dashboard::DomainBucket,
            crate::routes::enterprise_dashboard::TitleBucket,
            crate::routes::enterprise_dashboard::PlatformStatsResponse,
            crate::routes::enterprise_dashboard::InterestRequestsBreakdown,
            crate::routes::enterprise_dashboard::MyStatsResponse,
            // gamification
            crate::routes::gamification::SkillLeaf,
            crate::routes::gamification::DomainBranch,
            crate::routes::gamification::SkillTreeUser,
            crate::routes::gamification::SkillTreeResponse,
            crate::routes::gamification::ActivityDay,
            crate::routes::gamification::HeatmapSummary,
            crate::routes::gamification::HeatmapResponse,
            // public API v1
            crate::models::BadgeWithEarnedAt,
            crate::routes::public_api::V1Meta,
            crate::routes::public_api::V1UserProfile,
            crate::routes::public_api::V1UserProfileResponse,
            crate::routes::public_api::V1UserBadgesResponse,
            crate::routes::public_api::V1SkillLeaf,
            crate::routes::public_api::V1DomainBranch,
            crate::routes::public_api::V1UserSkillsResponse,
            // review queue
            crate::services::review_queue::ReviewTask,
            crate::services::reviews::SubmitOutcome,
            crate::routes::review_queue::TasksListResponse,
            crate::routes::review_queue::TaskResponse,
            crate::routes::review_queue::ClaimResponse,
            crate::routes::review_queue::SubmitReviewBody,
            crate::routes::review_queue::SubmitReviewResponse,
            crate::routes::review_queue::ReviewRow,
            crate::routes::review_queue::ReviewsListResponse,
            // talent search v3
            crate::routes::talent_search_v3::TalentRow,
            crate::routes::talent_search_v3::SearchV3Pagination,
            crate::routes::talent_search_v3::FiltersApplied,
            crate::routes::talent_search_v3::SearchV3Data,
            crate::routes::talent_search_v3::SearchV3Response,
            // explore
            crate::routes::explore::ExploreItem,
            crate::routes::explore::ExplorePage,
            crate::routes::explore::ExploreResponse,
            // admin dashboard
            crate::routes::admin_dashboard::AdminOverviewResponse,
            crate::routes::admin_dashboard::PurchaseBreakdownRow,
            crate::routes::admin_dashboard::AdminFinancialResponse,
            crate::routes::admin_dashboard::ModerationQueueResponse,
            crate::routes::admin_dashboard::DbPoolInfo,
            crate::routes::admin_dashboard::WsInfo,
            crate::routes::admin_dashboard::OpsHealthResponse,
            // admin community
            crate::routes::admin_community::RejectRequest,
            crate::routes::admin_community::CreatorSummary,
            crate::routes::admin_community::EnrichedChallenge,
            crate::routes::admin_community::PendingReviewResponse,
            crate::routes::admin_community::AdminChallengeDecisionResponse,
            // DM
            crate::services::dm::DmConversation,
            crate::services::dm::DmMessage,
            crate::services::dm::ConversationSummary,
            crate::services::dm::UserBlock,
            crate::routes::dm::OpenConversationBody,
            crate::routes::dm::OpenConversationResponse,
            crate::routes::dm::ConversationsResponse,
            crate::routes::dm::MessagesResponse,
            crate::routes::dm::SendMessageBody,
            crate::routes::dm::SendMessageResponse,
            crate::routes::dm::MarkReadResponse,
            crate::routes::dm::BlockBody,
            crate::routes::dm::BlockedResponse,
            crate::routes::dm::UnblockedResponse,
            crate::routes::dm::BlocksResponse,
            // talent_search
            crate::routes::talent_search::TalentSearchEntry,
            crate::routes::talent_search::TalentSearchResponse,
            crate::routes::talent_search::TalentCardTopSkill,
            crate::routes::talent_search::TalentCardResponse,
            // forum
            crate::routes::forum::CreatePostBody,
            crate::routes::forum::EditPostBody,
            crate::routes::forum::AcceptAnswerBody,
            crate::routes::forum::TogglePinBody,
            crate::routes::forum::ToggleLockBody,
            // admin users
            crate::routes::admin_users::RecomputeBody,
            crate::routes::admin_users::RankOverrideBody,
            // projects
            crate::routes::projects::AddContributorBody,
            crate::routes::projects::SetCuratedBody,
            crate::routes::projects::MarkInterestedBody,
            // community
            crate::routes::community::CreateCommunityChallenge,
            crate::routes::community::UpdateCommunityChallenge,
            // slices
            crate::routes::slices::ClaimAsTeamBody,
            // enterprise_pipeline
            crate::routes::enterprise_pipeline::AddEntryBody,
            crate::routes::enterprise_pipeline::UpdateEntryBody,
            // moderation
            crate::routes::moderation::RejectBody,
            crate::routes::moderation::ReasonBody,
            crate::routes::moderation::ModeratePostBody,
            crate::routes::moderation::MuteUserBody,
            // tournament
            crate::routes::tournament::StatusBody,
            crate::routes::tournament::RegisterBody,
            crate::routes::tournament::ScoreBody,
            // user_profile
            crate::routes::user_profile::UpdateProfileRequest,
            crate::routes::user_profile::UpdateDisplayNameRequest,
            crate::routes::user_profile::UpdateSkillDomainRequest,
            crate::routes::user_profile::UpdatePrivacyRequest,
            crate::routes::user_profile::PrivacySettings,
            // profile_extras
            crate::routes::profile_extras::AvailabilityBody,
            crate::routes::profile_extras::LanguageBody,
            // social
            crate::routes::social::CreateCommentBody,
            crate::routes::social::EditCommentBody,
            crate::routes::social::ToggleReactionBody,
            crate::routes::social::TagMapBody,
            // webauthn
            crate::routes::webauthn::RegisterStartRequest,
            crate::routes::webauthn::RenameRequest,
            crate::routes::webauthn::LoginStartRequest,
            // developer
            crate::routes::developer::CreateKeyRequest,
            crate::routes::developer::CreateWebhookRequest,
            crate::routes::developer::UpdateWebhookRequest,
            // bounties
            crate::routes::bounties::CreateBountyBody,
            crate::routes::bounties::SubmitPrBody,
            // admin ops
            crate::routes::admin_ops::SweepQuery,
            crate::routes::admin_ops::GdprExportBody,
            crate::routes::admin_ops::ListEventsQuery,
            crate::routes::admin_ops::CreateEventBody,
        ),
    ),
    tags(
        (name = "auth",         description = "Authentication, session, 2FA, passkeys"),
        (name = "profile",      description = "Public + private user profile"),
        (name = "challenges",   description = "Challenges, submissions, review queue"),
        (name = "projects",     description = "Real OSS projects → slices → deliverables"),
        (name = "forum",        description = "Q&A forum with accepted answers"),
        (name = "dm",           description = "Direct messages"),
        (name = "social",       description = "Follows, contact requests, blocks"),
        (name = "guilds",       description = "Persistent teams, wars, applications"),
        (name = "feed",         description = "For-you feed + explore"),
        (name = "enterprise",   description = "B2B credits, invoices, KYC, SSO"),
        (name = "wallet",       description = "Talent payouts (Stripe Connect, Momo)"),
        (name = "moderation",   description = "Community moderation surface"),
        (name = "admin",        description = "Admin panel — requires 2FA + admin origin"),
        (name = "webhooks",     description = "Inbound webhooks (Stripe, GitHub, Brevo)"),
        (name = "health",       description = "Liveness, readiness, metrics"),
    ),
)]
pub struct ApiDoc;

/// Security-scheme modifier. Registers the two auth mechanisms used across
/// the API:
///
/// - **`cookie_auth`**  — the HttpOnly `access_token` cookie set by
///   `/api/auth/login` and refreshed by `/api/auth/refresh`. Used by both
///   frontends (skilluv-frontend, skilluv-admin).
/// - **`bearer_auth`** — API-key bearer token used by third parties on the
///   public API surface (`/api/v1/*`).
///
/// Individual handlers reference these via `security(("cookie_auth" = []))`
/// in their `#[utoipa::path]` annotation.
struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi
            .components
            .as_mut()
            .expect("components populated by derive");
        components.add_security_scheme(
            "cookie_auth",
            SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::new("access_token"))),
        );
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(HttpBuilder::new().scheme(HttpAuthScheme::Bearer).build()),
        );
    }
}

/// Attach the OpenAPI JSON endpoint + Swagger UI to a router.
///
/// The Swagger UI is exposed unconditionally in debug builds; in release
/// it's gated behind `SKILLUV_EXPOSE_SWAGGER=1` — set by the deployer for
/// staging, unset in prod so the schema doesn't leak the full route
/// surface to random scanners.
pub fn attach<S>(router: Router<S>) -> Router<S>
where
    S: Clone + Send + Sync + 'static,
{
    let expose_swagger = std::env::var("SKILLUV_EXPOSE_SWAGGER")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(cfg!(debug_assertions));

    let router = router.route("/api/openapi.json", axum::routing::get(openapi_json));

    if expose_swagger {
        router.merge(SwaggerUi::new("/api/docs").url("/api/openapi.json", ApiDoc::openapi()))
    } else {
        router
    }
}

async fn openapi_json() -> impl IntoResponse {
    axum::Json(ApiDoc::openapi())
}
